import type {
  EquipmentSlot,
  ItemId,
  MapVisualObjectId,
  NpcEntity,
  ResourceType,
  SkillId,
} from "./game";

const nowAssetPackPath = "/assets/Generated/now-pack";
const equipmentIconPath = "/assets/Generated/equipment-icons/items";
const wildernessMapAssetPath = "/assets/Generated/map-wilderness";
const hubFloorAssetPath = "/assets/Generated/hub-floors";
const hubCastleWallAssetPath = "/assets/Generated/hub-castle-walls";
const hubStructureAssetPath = "/assets/Generated/hub-structures/256";
const teleportAssetPath = "/assets/Generated/teleports";
const passageBlockerAssetPath = "/assets/Generated/passage-blockers";
const slimewardDungeonAssetPath = "/assets/Generated/Dungeon Generation";
const beginnerSkillEffectsPath = "/assets/Generated/beginner-skill-effects-50/sprites";
const firstClassSkillEffectsPath = "/assets/Generated/first-class-skill-effects";
const bladeSkillEffectsPath = `${firstClassSkillEffectsPath}/blade/sprites`;
const aegisSkillEffectsPath = `${firstClassSkillEffectsPath}/aegis/sprites`;
const hunterSkillEffectsPath = `${firstClassSkillEffectsPath}/hunter/sprites`;
const beastSkillEffectsPath = `${firstClassSkillEffectsPath}/beast/sprites`;
const elementalistSkillEffectsPath = `${firstClassSkillEffectsPath}/elementalist/sprites`;
const runecasterSkillEffectsPath = `${firstClassSkillEffectsPath}/runecaster/sprites`;
const lightbearerSkillEffectsPath = `${firstClassSkillEffectsPath}/lightbearer/sprites`;
const penitentSkillEffectsPath = `${firstClassSkillEffectsPath}/penitent/sprites`;
const wildernessMapFloor128AssetPath = `${wildernessMapAssetPath}/128`;
const hubFloor128AssetPath = `${hubFloorAssetPath}/New/128`;

export const INVENTORY_ITEM_ICON_SRC: Partial<Record<ItemId, string>> = {
  wood: `${nowAssetPackPath}/wood-node.png`,
  ore: `${nowAssetPackPath}/ore-node.png`,
  herb: `${nowAssetPackPath}/herb-node.png`,
  softwood: `${nowAssetPackPath}/wood-node.png`,
  copper_ore: `${nowAssetPackPath}/ore-node.png`,
  field_herb: `${nowAssetPackPath}/herb-node.png`,
  hardwood: `${nowAssetPackPath}/wood-node.png`,
  iron_ore: `${nowAssetPackPath}/ore-node.png`,
  redleaf_herb: `${nowAssetPackPath}/herb-node.png`,
  slime_gel_t1: `${nowAssetPackPath}/herb-node.png`,
  slime_core_t1: `${nowAssetPackPath}/ore-node.png`,
  bat_wing_t1: `${nowAssetPackPath}/wood-node.png`,
  bat_ear_t1: `${nowAssetPackPath}/wood-node.png`,
  spider_silk_t1: `${nowAssetPackPath}/herb-node.png`,
  spider_fang_t1: `${nowAssetPackPath}/ore-node.png`,
  goblin_ear_t1: `${nowAssetPackPath}/wood-node.png`,
  goblin_tooth_t1: `${nowAssetPackPath}/ore-node.png`,
  imp_horn_chip_t1: `${nowAssetPackPath}/ore-node.png`,
  imp_tail_t1: `${nowAssetPackPath}/wood-node.png`,
  wolf_pelt: `${nowAssetPackPath}/wood-node.png`,
  wolf_fang: `${nowAssetPackPath}/ore-node.png`,
  crawler_pebble_t1: `${nowAssetPackPath}/ore-node.png`,
  crawler_plate_t1: `${nowAssetPackPath}/ore-node.png`,
  moss_tuft_t1: `${nowAssetPackPath}/herb-node.png`,
  mossling_cap_t1: `${nowAssetPackPath}/herb-node.png`,
  goblin_ear_t2: `${nowAssetPackPath}/wood-node.png`,
  goblin_tooth_t2: `${nowAssetPackPath}/ore-node.png`,
  wisp_ash_t2: `${nowAssetPackPath}/ore-node.png`,
  wisp_ember_t2: `${nowAssetPackPath}/ore-node.png`,
  orc_tusk: `${nowAssetPackPath}/ore-node.png`,
  orc_hide: `${nowAssetPackPath}/wood-node.png`,
  minor_recovery_flask: `${beginnerSkillEffectsPath}/first_aid.png`,
  soldiers_recovery_flask: `${beginnerSkillEffectsPath}/rally_call.png`,
  hearty_trail_rations: `${nowAssetPackPath}/herb-node.png`,
  skirmisher_rations: `${nowAssetPackPath}/herb-node.png`,
  // equipment-icons-level-1-5-grid
  plain_charm: `${equipmentIconPath}/accessories/plain_charm.png`,
  scout_boots: `${equipmentIconPath}/scout/scout_boots.png`,
  scout_jacket: `${equipmentIconPath}/scout/scout_jacket.png`,
  scout_gloves: `${equipmentIconPath}/scout/scout_gloves.png`,
  scout_cap: `${equipmentIconPath}/scout/scout_cap.png`,
  scout_trousers: `${equipmentIconPath}/scout/scout_trousers.png`,
  guard_boots: `${equipmentIconPath}/guard/guard_boots.png`,
  guard_hauberk: `${equipmentIconPath}/guard/guard_hauberk.png`,
  guard_gloves: `${equipmentIconPath}/guard/guard_gloves.png`,
  guard_coif: `${equipmentIconPath}/guard/guard_coif.png`,
  guard_legguards: `${equipmentIconPath}/guard/guard_legguards.png`,
  training_sword: `${equipmentIconPath}/training/training_sword.png`,
  stalker_boots: `${equipmentIconPath}/stalker/stalker_boots.png`,
  stalker_vest: `${equipmentIconPath}/stalker/stalker_vest.png`,
  stalker_grips: `${equipmentIconPath}/stalker/stalker_grips.png`,
  stalker_mask: `${equipmentIconPath}/stalker/stalker_mask.png`,
  stalker_leggings: `${equipmentIconPath}/stalker/stalker_leggings.png`,
  vanguard_boots: `${equipmentIconPath}/vanguard/vanguard_boots.png`,
  vanguard_hauberk: `${equipmentIconPath}/vanguard/vanguard_hauberk.png`,
  vanguard_gloves: `${equipmentIconPath}/vanguard/vanguard_gloves.png`,
  vanguard_coif: `${equipmentIconPath}/vanguard/vanguard_coif.png`,
  vanguard_legguards: `${equipmentIconPath}/vanguard/vanguard_legguards.png`,
  // equipment-icons-level-10-armor-grid
  acolyte_sandals: `${equipmentIconPath}/acolyte/acolyte_sandals.png`,
  scholar_sandals: `${equipmentIconPath}/scholar/scholar_sandals.png`,
  acolyte_robe: `${equipmentIconPath}/acolyte/acolyte_robe.png`,
  scholar_robe: `${equipmentIconPath}/scholar/scholar_robe.png`,
  acolyte_wraps: `${equipmentIconPath}/acolyte/acolyte_wraps.png`,
  scholar_gloves: `${equipmentIconPath}/scholar/scholar_gloves.png`,
  acolyte_hood: `${equipmentIconPath}/acolyte/acolyte_hood.png`,
  scholar_hood: `${equipmentIconPath}/scholar/scholar_hood.png`,
  acolyte_pants: `${equipmentIconPath}/acolyte/acolyte_pants.png`,
  scholar_pants: `${equipmentIconPath}/scholar/scholar_pants.png`,
  ravager_boots: `${equipmentIconPath}/ravager/ravager_boots.png`,
  trailrunner_boots: `${equipmentIconPath}/trailrunner/trailrunner_boots.png`,
  ravager_vest: `${equipmentIconPath}/ravager/ravager_vest.png`,
  trailrunner_jacket: `${equipmentIconPath}/trailrunner/trailrunner_jacket.png`,
  ravager_grips: `${equipmentIconPath}/ravager/ravager_grips.png`,
  trailrunner_gloves: `${equipmentIconPath}/trailrunner/trailrunner_gloves.png`,
  ravager_mask: `${equipmentIconPath}/ravager/ravager_mask.png`,
  trailrunner_cap: `${equipmentIconPath}/trailrunner/trailrunner_cap.png`,
  ravager_leggings: `${equipmentIconPath}/ravager/ravager_leggings.png`,
  trailrunner_trousers: `${equipmentIconPath}/trailrunner/trailrunner_trousers.png`,
  ironmarch_boots: `${equipmentIconPath}/ironmarch/ironmarch_boots.png`,
  wardmail_boots: `${equipmentIconPath}/wardmail/wardmail_boots.png`,
  ironmarch_hauberk: `${equipmentIconPath}/ironmarch/ironmarch_hauberk.png`,
  wardmail_hauberk: `${equipmentIconPath}/wardmail/wardmail_hauberk.png`,
  ironmarch_gloves: `${equipmentIconPath}/ironmarch/ironmarch_gloves.png`,
  wardmail_gloves: `${equipmentIconPath}/wardmail/wardmail_gloves.png`,
  ironmarch_coif: `${equipmentIconPath}/ironmarch/ironmarch_coif.png`,
  wardmail_coif: `${equipmentIconPath}/wardmail/wardmail_coif.png`,
  ironmarch_legguards: `${equipmentIconPath}/ironmarch/ironmarch_legguards.png`,
  wardmail_legguards: `${equipmentIconPath}/wardmail/wardmail_legguards.png`,
  bulwark_sabatons: `${equipmentIconPath}/bulwark/bulwark_sabatons.png`,
  warplate_sabatons: `${equipmentIconPath}/warplate/warplate_sabatons.png`,
  bulwark_cuirass: `${equipmentIconPath}/bulwark/bulwark_cuirass.png`,
  warplate_cuirass: `${equipmentIconPath}/warplate/warplate_cuirass.png`,
  bulwark_gauntlets: `${equipmentIconPath}/bulwark/bulwark_gauntlets.png`,
  warplate_gauntlets: `${equipmentIconPath}/warplate/warplate_gauntlets.png`,
  bulwark_helm: `${equipmentIconPath}/bulwark/bulwark_helm.png`,
  warplate_helm: `${equipmentIconPath}/warplate/warplate_helm.png`,
  bulwark_greaves: `${equipmentIconPath}/bulwark/bulwark_greaves.png`,
  warplate_greaves: `${equipmentIconPath}/warplate/warplate_greaves.png`,
  // equipment-icons-level-10-15-weapons-offhands-grid
  holy_lantern: `${equipmentIconPath}/holy/holy_lantern.png`,
  sacrificial_dagger: `${equipmentIconPath}/sacrificial/sacrificial_dagger.png`,
  simple_talisman: `${equipmentIconPath}/simple/simple_talisman.png`,
  wooden_shield: `${equipmentIconPath}/wooden/wooden_shield.png`,
  apprentice_orb: `${equipmentIconPath}/apprentice/apprentice_orb.png`,
  claw_gauntlets: `${equipmentIconPath}/claw/claw_gauntlets.png`,
  guard_mace: `${equipmentIconPath}/guard/guard_mace.png`,
  holy_mace: `${equipmentIconPath}/holy/holy_mace.png`,
  iron_sword: `${equipmentIconPath}/iron/iron_sword.png`,
  rune_lantern: `${equipmentIconPath}/rune/rune_lantern.png`,
  short_bow: `${equipmentIconPath}/short/short_bow.png`,
  thorn_whip: `${equipmentIconPath}/thorn/thorn_whip.png`,
  bright_lantern: `${equipmentIconPath}/bright/bright_lantern.png`,
  reinforced_shield: `${equipmentIconPath}/reinforced/reinforced_shield.png`,
  ritual_dagger: `${equipmentIconPath}/ritual/ritual_dagger.png`,
  warded_talisman: `${equipmentIconPath}/warded/warded_talisman.png`,
  adept_orb: `${equipmentIconPath}/adept/adept_orb.png`,
  barbed_whip: `${equipmentIconPath}/barbed/barbed_whip.png`,
  bastion_mace: `${equipmentIconPath}/bastion/bastion_mace.png`,
  etched_rune_lantern: `${equipmentIconPath}/etched/etched_rune_lantern.png`,
  reinforced_bow: `${equipmentIconPath}/reinforced/reinforced_bow.png`,
  sanctified_mace: `${equipmentIconPath}/sanctified/sanctified_mace.png`,
  steel_claws: `${equipmentIconPath}/steel/steel_claws.png`,
  steel_sword: `${equipmentIconPath}/steel/steel_sword.png`,
  // equipment-icons-level-15-armor-grid
  adept_sandals: `${equipmentIconPath}/adept/adept_sandals.png`,
  blessed_sandals: `${equipmentIconPath}/blessed/blessed_sandals.png`,
  adept_robe: `${equipmentIconPath}/adept/adept_robe.png`,
  blessed_robe: `${equipmentIconPath}/blessed/blessed_robe.png`,
  adept_gloves: `${equipmentIconPath}/adept/adept_gloves.png`,
  blessed_wraps: `${equipmentIconPath}/blessed/blessed_wraps.png`,
  adept_hood: `${equipmentIconPath}/adept/adept_hood.png`,
  blessed_hood: `${equipmentIconPath}/blessed/blessed_hood.png`,
  adept_pants: `${equipmentIconPath}/adept/adept_pants.png`,
  blessed_pants: `${equipmentIconPath}/blessed/blessed_pants.png`,
  pathfinder_boots: `${equipmentIconPath}/pathfinder/pathfinder_boots.png`,
  striker_boots: `${equipmentIconPath}/striker/striker_boots.png`,
  pathfinder_jacket: `${equipmentIconPath}/pathfinder/pathfinder_jacket.png`,
  striker_vest: `${equipmentIconPath}/striker/striker_vest.png`,
  pathfinder_gloves: `${equipmentIconPath}/pathfinder/pathfinder_gloves.png`,
  striker_grips: `${equipmentIconPath}/striker/striker_grips.png`,
  pathfinder_cap: `${equipmentIconPath}/pathfinder/pathfinder_cap.png`,
  striker_mask: `${equipmentIconPath}/striker/striker_mask.png`,
  pathfinder_trousers: `${equipmentIconPath}/pathfinder/pathfinder_trousers.png`,
  striker_leggings: `${equipmentIconPath}/striker/striker_leggings.png`,
  marshal_boots: `${equipmentIconPath}/marshal/marshal_boots.png`,
  sentinel_boots: `${equipmentIconPath}/sentinel/sentinel_boots.png`,
  marshal_hauberk: `${equipmentIconPath}/marshal/marshal_hauberk.png`,
  sentinel_hauberk: `${equipmentIconPath}/sentinel/sentinel_hauberk.png`,
  marshal_gloves: `${equipmentIconPath}/marshal/marshal_gloves.png`,
  sentinel_gloves: `${equipmentIconPath}/sentinel/sentinel_gloves.png`,
  marshal_coif: `${equipmentIconPath}/marshal/marshal_coif.png`,
  sentinel_coif: `${equipmentIconPath}/sentinel/sentinel_coif.png`,
  marshal_legguards: `${equipmentIconPath}/marshal/marshal_legguards.png`,
  sentinel_legguards: `${equipmentIconPath}/sentinel/sentinel_legguards.png`,
  bastion_sabatons: `${equipmentIconPath}/bastion/bastion_sabatons.png`,
  breaker_sabatons: `${equipmentIconPath}/breaker/breaker_sabatons.png`,
  bastion_cuirass: `${equipmentIconPath}/bastion/bastion_cuirass.png`,
  breaker_cuirass: `${equipmentIconPath}/breaker/breaker_cuirass.png`,
  bastion_gauntlets: `${equipmentIconPath}/bastion/bastion_gauntlets.png`,
  breaker_gauntlets: `${equipmentIconPath}/breaker/breaker_gauntlets.png`,
  bastion_helm: `${equipmentIconPath}/bastion/bastion_helm.png`,
  breaker_helm: `${equipmentIconPath}/breaker/breaker_helm.png`,
  bastion_greaves: `${equipmentIconPath}/bastion/bastion_greaves.png`,
  breaker_greaves: `${equipmentIconPath}/breaker/breaker_greaves.png`,
  // equipment-icons-level-20-armor-grid
  arcanist_sandals: `${equipmentIconPath}/arcanist/arcanist_sandals.png`,
  sanctuary_sandals: `${equipmentIconPath}/sanctuary/sanctuary_sandals.png`,
  arcanist_robe: `${equipmentIconPath}/arcanist/arcanist_robe.png`,
  sanctuary_robe: `${equipmentIconPath}/sanctuary/sanctuary_robe.png`,
  arcanist_gloves: `${equipmentIconPath}/arcanist/arcanist_gloves.png`,
  sanctuary_wraps: `${equipmentIconPath}/sanctuary/sanctuary_wraps.png`,
  arcanist_hood: `${equipmentIconPath}/arcanist/arcanist_hood.png`,
  sanctuary_hood: `${equipmentIconPath}/sanctuary/sanctuary_hood.png`,
  arcanist_pants: `${equipmentIconPath}/arcanist/arcanist_pants.png`,
  sanctuary_pants: `${equipmentIconPath}/sanctuary/sanctuary_pants.png`,
  duelist_boots: `${equipmentIconPath}/duelist/duelist_boots.png`,
  wayfarer_boots: `${equipmentIconPath}/wayfarer/wayfarer_boots.png`,
  duelist_vest: `${equipmentIconPath}/duelist/duelist_vest.png`,
  wayfarer_jacket: `${equipmentIconPath}/wayfarer/wayfarer_jacket.png`,
  duelist_grips: `${equipmentIconPath}/duelist/duelist_grips.png`,
  wayfarer_gloves: `${equipmentIconPath}/wayfarer/wayfarer_gloves.png`,
  duelist_mask: `${equipmentIconPath}/duelist/duelist_mask.png`,
  wayfarer_cap: `${equipmentIconPath}/wayfarer/wayfarer_cap.png`,
  duelist_leggings: `${equipmentIconPath}/duelist/duelist_leggings.png`,
  wayfarer_trousers: `${equipmentIconPath}/wayfarer/wayfarer_trousers.png`,
  frontline_boots: `${equipmentIconPath}/frontline/frontline_boots.png`,
  ironward_boots: `${equipmentIconPath}/ironward/ironward_boots.png`,
  frontline_hauberk: `${equipmentIconPath}/frontline/frontline_hauberk.png`,
  ironward_hauberk: `${equipmentIconPath}/ironward/ironward_hauberk.png`,
  frontline_gloves: `${equipmentIconPath}/frontline/frontline_gloves.png`,
  ironward_gloves: `${equipmentIconPath}/ironward/ironward_gloves.png`,
  frontline_coif: `${equipmentIconPath}/frontline/frontline_coif.png`,
  ironward_coif: `${equipmentIconPath}/ironward/ironward_coif.png`,
  frontline_legguards: `${equipmentIconPath}/frontline/frontline_legguards.png`,
  ironward_legguards: `${equipmentIconPath}/ironward/ironward_legguards.png`,
  conqueror_sabatons: `${equipmentIconPath}/conqueror/conqueror_sabatons.png`,
  ironhold_sabatons: `${equipmentIconPath}/ironhold/ironhold_sabatons.png`,
  conqueror_cuirass: `${equipmentIconPath}/conqueror/conqueror_cuirass.png`,
  ironhold_cuirass: `${equipmentIconPath}/ironhold/ironhold_cuirass.png`,
  conqueror_gauntlets: `${equipmentIconPath}/conqueror/conqueror_gauntlets.png`,
  ironhold_gauntlets: `${equipmentIconPath}/ironhold/ironhold_gauntlets.png`,
  conqueror_helm: `${equipmentIconPath}/conqueror/conqueror_helm.png`,
  ironhold_helm: `${equipmentIconPath}/ironhold/ironhold_helm.png`,
  conqueror_greaves: `${equipmentIconPath}/conqueror/conqueror_greaves.png`,
  ironhold_greaves: `${equipmentIconPath}/ironhold/ironhold_greaves.png`,
  // equipment-icons-level-20-weapons-offhands-grid
  greater_talisman: `${equipmentIconPath}/greater/greater_talisman.png`,
  oath_dagger: `${equipmentIconPath}/oath/oath_dagger.png`,
  radiant_lantern: `${equipmentIconPath}/radiant/radiant_lantern.png`,
  tower_shield: `${equipmentIconPath}/tower/tower_shield.png`,
  bloodthorn_whip: `${equipmentIconPath}/bloodthorn/bloodthorn_whip.png`,
  dawn_mace: `${equipmentIconPath}/dawn/dawn_mace.png`,
  deep_rune_lantern: `${equipmentIconPath}/deep/deep_rune_lantern.png`,
  ironhold_mace: `${equipmentIconPath}/ironhold/ironhold_mace.png`,
  rending_claws: `${equipmentIconPath}/rending/rending_claws.png`,
  storm_orb: `${equipmentIconPath}/storm/storm_orb.png`,
  veteran_sword: `${equipmentIconPath}/veteran/veteran_sword.png`,
  veteran_warbow: `${equipmentIconPath}/veteran/veteran_warbow.png`,
};

export const EMPTY_EQUIPMENT_SLOT_ICON_SRC: Partial<Record<EquipmentSlot, string>> = {
  mainHand: `${nowAssetPackPath}/empty-main-hand.png`,
  offhand: `${nowAssetPackPath}/empty-offhand.png`,
};

export const RESOURCE_ICON_SRC = {
  wood: `${nowAssetPackPath}/wood-node.png`,
  ore: `${nowAssetPackPath}/ore-node.png`,
  herb: `${nowAssetPackPath}/herb-node.png`,
} satisfies Record<ResourceType, string>;

export const NPC_ICON_SRC: Partial<Record<NpcEntity["npcRole"], string>> = {
  quest_giver: `${nowAssetPackPath}/quest-giver.png`,
  class_mentor: `${nowAssetPackPath}/class-mentor.png`,
  merchant: `${nowAssetPackPath}/merchant.png`,
  smith: `${nowAssetPackPath}/smith.png`,
  bank_chest: `${slimewardDungeonAssetPath}/dungeon-chest-closed-64.png`,
  dog: `${nowAssetPackPath}/dog.png`,
  dungeon_chest_closed: `${slimewardDungeonAssetPath}/dungeon-chest-closed-64.png`,
  dungeon_chest_open: `${slimewardDungeonAssetPath}/dungeon-chest-open-64.png`,
};

export const WILDERNESS_MAP_TILE_SRC = {
  grassA: `${wildernessMapAssetPath}/grass-a.png`,
  grassB: `${wildernessMapAssetPath}/grass-b.png`,
  grass128: `${wildernessMapFloor128AssetPath}/forest-grass-floor-atlas-128.png`,
  grassDetail128: `${wildernessMapFloor128AssetPath}/forest-grass-detail-floor-atlas-128.png`,
  grassBackup128: `${wildernessMapFloor128AssetPath}/forest-grass-backup-floor-atlas-128.png`,
  grassFlowers128: `${wildernessMapFloor128AssetPath}/forest-grass-flowers-floor-atlas-128.png`,
  tree: `${wildernessMapAssetPath}/tree.png`,
  bush: `${wildernessMapAssetPath}/bush.png`,
} as const;

export const HUB_MAP_TILE_SRC = {
  stone: `${hubFloorAssetPath}/hub-city-stone-seamless.png`,
  grass128: `${hubFloor128AssetPath}/hub-outside-grass-floor-atlas-128.png`,
  stone128: `${hubFloor128AssetPath}/hub-stone-floor-atlas-128.png`,
} as const;

export const HUB_WALL_TILE_SRC = {
  north: `${hubCastleWallAssetPath}/castle-wall-north.png`,
  east: `${hubCastleWallAssetPath}/castle-wall-east.png`,
  south: `${hubCastleWallAssetPath}/castle-wall-south.png`,
  west: `${hubCastleWallAssetPath}/castle-wall-west.png`,
} as const;

export const MAP_VISUAL_OBJECT_SRC: Record<MapVisualObjectId, string> = {
  hub_house: `${hubStructureAssetPath}/hub_house.png`,
  hub_cabin: `${hubStructureAssetPath}/hub_cabin.png`,
  hub_tent: `${hubStructureAssetPath}/hub_tent.png`,
  hub_dock_shore_connector: `${hubStructureAssetPath}/hub_dock_shore_connector.png`,
  passage_gate_closed: `${passageBlockerAssetPath}/passage_gate_closed_edge_v2_100x350.png`,
  passage_gate_open: `${passageBlockerAssetPath}/passage_gate_open_faces_v2_100x350.png`,
  passage_blocker_collapsed_column: `${passageBlockerAssetPath}/passage_blocker_collapsed_column_100x350.png`,
  passage_blocker_repaired_column: `${passageBlockerAssetPath}/passage_blocker_repaired_column_100x350.png`,
  slime_covered_stone: `${slimewardDungeonAssetPath}/slime-covered-stone-64.png`,
  azure_slime_rock_cluster: `${slimewardDungeonAssetPath}/azure-slime-rock-cluster-128.png`,
};

export const SKILL_VISUAL_ICON_SRC: Partial<Record<SkillId, string>> = {
  throw_rock: `${beginnerSkillEffectsPath}/throw_rock.png`,
  kick: `${beginnerSkillEffectsPath}/kick.png`,
  guard_up: `${beginnerSkillEffectsPath}/guard_up.png`,
  first_aid: `${beginnerSkillEffectsPath}/first_aid.png`,
  deep_breath: `${beginnerSkillEffectsPath}/deep_breath.png`,
  rally_call: `${beginnerSkillEffectsPath}/rally_call.png`,
  field_hands: `${beginnerSkillEffectsPath}/field_hands.png`,
  quick_step: `${beginnerSkillEffectsPath}/quick_step.png`,
  duelist_challenge: `${bladeSkillEffectsPath}/duelist_challenge.png`,
  second_wind: `${bladeSkillEffectsPath}/second_wind.png`,
  blade_parry: `${bladeSkillEffectsPath}/blade_parry.png`,
  edge_focus: `${bladeSkillEffectsPath}/edge_focus.png`,
  press_the_opening: `${bladeSkillEffectsPath}/press_the_opening_caster.png`,
  woodcutter_rhythm: `${bladeSkillEffectsPath}/woodcutter_rhythm.png`,
  flash_step: `${bladeSkillEffectsPath}/flash_step.png`,
  sweeping_strike: `${bladeSkillEffectsPath}/sweeping_strike.png`,
  shield_challenge: `${aegisSkillEffectsPath}/shield_challenge.png`,
  hold_fast: `${aegisSkillEffectsPath}/hold_fast.png`,
  guard_wall: `${aegisSkillEffectsPath}/guard_wall.png`,
  iron_stance: `${aegisSkillEffectsPath}/iron_stance.png`,
  shield_formation: `${aegisSkillEffectsPath}/shield_formation_caster.png`,
  stonebreaker_rhythm: `${aegisSkillEffectsPath}/stonebreaker_rhythm.png`,
  shield_rush: `${aegisSkillEffectsPath}/shield_rush.png`,
  shield_shockwave: `${aegisSkillEffectsPath}/shield_shockwave.png`,
  pinning_shot: `${hunterSkillEffectsPath}/pinning_shot.png`,
  fake_death: `${hunterSkillEffectsPath}/fake_death.png`,
  evasive_instinct: `${hunterSkillEffectsPath}/evasive_instinct.png`,
  hunters_focus: `${hunterSkillEffectsPath}/hunters_focus.png`,
  poison_coating: `${hunterSkillEffectsPath}/poison_coating_caster.png`,
  herbalist_rhythm: `${hunterSkillEffectsPath}/herbalist_rhythm.png`,
  skirmish_shot: `${hunterSkillEffectsPath}/skirmish_shot.png`,
  arrow_burst: `${hunterSkillEffectsPath}/arrow_burst.png`,
  threatening_roar: `${beastSkillEffectsPath}/threatening_roar.png`,
  blood_feast: `${beastSkillEffectsPath}/blood_feast.png`,
  rugged_hide: `${beastSkillEffectsPath}/rugged_hide.png`,
  feral_surge: `${beastSkillEffectsPath}/feral_surge.png`,
  pack_frenzy: `${beastSkillEffectsPath}/pack_frenzy_caster.png`,
  stoneclaw_rhythm: `${beastSkillEffectsPath}/stoneclaw_rhythm.png`,
  pounce: `${beastSkillEffectsPath}/pounce.png`,
  maul_sweep: `${beastSkillEffectsPath}/maul_sweep.png`,
  elemental_bolt: `${elementalistSkillEffectsPath}/elemental_bolt.png`,
  mana_shield: `${elementalistSkillEffectsPath}/mana_shield.png`,
  frost_armor: `${elementalistSkillEffectsPath}/frost_armor.png`,
  overcharge: `${elementalistSkillEffectsPath}/overcharge.png`,
  arcane_conduit: `${elementalistSkillEffectsPath}/arcane_conduit_caster.png`,
  emberwood_rhythm: `${elementalistSkillEffectsPath}/emberwood_rhythm.png`,
  flame_step: `${elementalistSkillEffectsPath}/flame_step.png`,
  fire_burst: `${elementalistSkillEffectsPath}/fire_burst.png`,
  binding_rune: `${runecasterSkillEffectsPath}/binding_rune.png`,
  rune_lance: `${runecasterSkillEffectsPath}/rune_lance.png`,
  warding_glyph: `${runecasterSkillEffectsPath}/warding_glyph.png`,
  rewind_rune: `${runecasterSkillEffectsPath}/rewind_rune.png`,
  runic_focus: `${runecasterSkillEffectsPath}/runic_focus.png`,
  leyline_matrix: `${runecasterSkillEffectsPath}/leyline_matrix_caster.png`,
  stone_sigil_rhythm: `${runecasterSkillEffectsPath}/stone_sigil_rhythm.png`,
  rune_step: `${runecasterSkillEffectsPath}/rune_step.png`,
  blinding_ray: `${lightbearerSkillEffectsPath}/blinding_ray.png`,
  light_mend: `${lightbearerSkillEffectsPath}/light_mend.png`,
  sanctuary_veil: `${lightbearerSkillEffectsPath}/sanctuary_veil.png`,
  guiding_light: `${lightbearerSkillEffectsPath}/guiding_light.png`,
  radiant_benediction: `${lightbearerSkillEffectsPath}/radiant_benediction_caster.png`,
  herbalist_hymn: `${lightbearerSkillEffectsPath}/herbalist_hymn.png`,
  dawn_step: `${lightbearerSkillEffectsPath}/dawn_step.png`,
  circle_of_renewal: `${lightbearerSkillEffectsPath}/circle_of_renewal.png`,
  whip_prison: `${penitentSkillEffectsPath}/whip_prison_caster.png`,
  flagellant_lash: `${penitentSkillEffectsPath}/flagellant_lash.png`,
  martyrs_veil: `${penitentSkillEffectsPath}/martyrs_veil.png`,
  penitents_gift: `${penitentSkillEffectsPath}/penitents_gift.png`,
  eternal_hope: `${penitentSkillEffectsPath}/eternal_hope.png`,
  burdened_benediction: `${penitentSkillEffectsPath}/burdened_benediction_caster.png`,
  woodcutting_penance: `${penitentSkillEffectsPath}/woodcutting_penance.png`,
  atonement_step: `${penitentSkillEffectsPath}/atonement_step.png`,
};

export type SkillVisualPresentation = {
  src: string;
  width: number;
  height: number;
  targetedSrc?: string;
  targetedWidth?: number;
  targetedHeight?: number;
  endOpacity?: number;
};

export const SKILL_VISUAL_PRESENTATION: Partial<
  Record<SkillId, SkillVisualPresentation>
> = {
  duelist_challenge: {
    src: `${bladeSkillEffectsPath}/duelist_challenge.png`,
    width: 84,
    height: 84,
  },
  second_wind: {
    src: `${bladeSkillEffectsPath}/second_wind.png`,
    width: 76,
    height: 76,
  },
  blade_parry: {
    src: `${bladeSkillEffectsPath}/blade_parry.png`,
    width: 80,
    height: 80,
  },
  edge_focus: {
    src: `${bladeSkillEffectsPath}/edge_focus.png`,
    width: 78,
    height: 78,
  },
  press_the_opening: {
    src: `${bladeSkillEffectsPath}/press_the_opening_caster.png`,
    width: 92,
    height: 92,
    targetedSrc: `${bladeSkillEffectsPath}/press_the_opening_companion.png`,
    targetedWidth: 58,
    targetedHeight: 58,
  },
  woodcutter_rhythm: {
    src: `${bladeSkillEffectsPath}/woodcutter_rhythm.png`,
    width: 82,
    height: 82,
  },
  flash_step: {
    src: `${bladeSkillEffectsPath}/flash_step.png`,
    width: 80,
    height: 80,
  },
  sweeping_strike: {
    src: `${bladeSkillEffectsPath}/sweeping_strike.png`,
    width: 96,
    height: 96,
  },
  shield_challenge: {
    src: `${aegisSkillEffectsPath}/shield_challenge.png`,
    width: 84,
    height: 84,
  },
  hold_fast: {
    src: `${aegisSkillEffectsPath}/hold_fast.png`,
    width: 88,
    height: 88,
  },
  guard_wall: {
    src: `${aegisSkillEffectsPath}/guard_wall.png`,
    width: 86,
    height: 86,
  },
  iron_stance: {
    src: `${aegisSkillEffectsPath}/iron_stance.png`,
    width: 82,
    height: 82,
  },
  shield_formation: {
    src: `${aegisSkillEffectsPath}/shield_formation_caster.png`,
    width: 96,
    height: 96,
    targetedSrc: `${aegisSkillEffectsPath}/shield_formation_companion.png`,
    targetedWidth: 60,
    targetedHeight: 60,
  },
  stonebreaker_rhythm: {
    src: `${aegisSkillEffectsPath}/stonebreaker_rhythm.png`,
    width: 82,
    height: 82,
  },
  shield_rush: {
    src: `${aegisSkillEffectsPath}/shield_rush.png`,
    width: 84,
    height: 84,
  },
  shield_shockwave: {
    src: `${aegisSkillEffectsPath}/shield_shockwave.png`,
    width: 100,
    height: 100,
  },
  pinning_shot: {
    src: `${hunterSkillEffectsPath}/pinning_shot.png`,
    width: 84,
    height: 84,
  },
  fake_death: {
    src: `${hunterSkillEffectsPath}/fake_death.png`,
    width: 82,
    height: 82,
  },
  evasive_instinct: {
    src: `${hunterSkillEffectsPath}/evasive_instinct.png`,
    width: 82,
    height: 82,
  },
  hunters_focus: {
    src: `${hunterSkillEffectsPath}/hunters_focus.png`,
    width: 84,
    height: 84,
  },
  poison_coating: {
    src: `${hunterSkillEffectsPath}/poison_coating_caster.png`,
    width: 96,
    height: 96,
    targetedSrc: `${hunterSkillEffectsPath}/poison_coating_companion.png`,
    targetedWidth: 60,
    targetedHeight: 60,
  },
  herbalist_rhythm: {
    src: `${hunterSkillEffectsPath}/herbalist_rhythm.png`,
    width: 82,
    height: 82,
  },
  skirmish_shot: {
    src: `${hunterSkillEffectsPath}/skirmish_shot.png`,
    width: 84,
    height: 84,
  },
  arrow_burst: {
    src: `${hunterSkillEffectsPath}/arrow_burst.png`,
    width: 100,
    height: 100,
  },
  threatening_roar: {
    src: `${beastSkillEffectsPath}/threatening_roar.png`,
    width: 88,
    height: 88,
  },
  blood_feast: {
    src: `${beastSkillEffectsPath}/blood_feast.png`,
    width: 84,
    height: 84,
  },
  rugged_hide: {
    src: `${beastSkillEffectsPath}/rugged_hide.png`,
    width: 86,
    height: 86,
  },
  feral_surge: {
    src: `${beastSkillEffectsPath}/feral_surge.png`,
    width: 84,
    height: 84,
  },
  pack_frenzy: {
    src: `${beastSkillEffectsPath}/pack_frenzy_caster.png`,
    width: 96,
    height: 96,
    targetedSrc: `${beastSkillEffectsPath}/pack_frenzy_companion.png`,
    targetedWidth: 60,
    targetedHeight: 60,
  },
  stoneclaw_rhythm: {
    src: `${beastSkillEffectsPath}/stoneclaw_rhythm.png`,
    width: 82,
    height: 82,
  },
  pounce: {
    src: `${beastSkillEffectsPath}/pounce.png`,
    width: 86,
    height: 86,
  },
  maul_sweep: {
    src: `${beastSkillEffectsPath}/maul_sweep.png`,
    width: 100,
    height: 100,
  },
  elemental_bolt: {
    src: `${elementalistSkillEffectsPath}/elemental_bolt.png`,
    width: 84,
    height: 84,
  },
  mana_shield: {
    src: `${elementalistSkillEffectsPath}/mana_shield.png`,
    width: 88,
    height: 88,
  },
  frost_armor: {
    src: `${elementalistSkillEffectsPath}/frost_armor.png`,
    width: 86,
    height: 86,
  },
  overcharge: {
    src: `${elementalistSkillEffectsPath}/overcharge.png`,
    width: 86,
    height: 86,
  },
  arcane_conduit: {
    src: `${elementalistSkillEffectsPath}/arcane_conduit_caster.png`,
    width: 96,
    height: 96,
    targetedSrc: `${elementalistSkillEffectsPath}/arcane_conduit_companion.png`,
    targetedWidth: 60,
    targetedHeight: 60,
  },
  emberwood_rhythm: {
    src: `${elementalistSkillEffectsPath}/emberwood_rhythm.png`,
    width: 82,
    height: 82,
  },
  flame_step: {
    src: `${elementalistSkillEffectsPath}/flame_step.png`,
    width: 86,
    height: 86,
  },
  fire_burst: {
    src: `${elementalistSkillEffectsPath}/fire_burst.png`,
    width: 100,
    height: 100,
  },
  binding_rune: {
    src: `${runecasterSkillEffectsPath}/binding_rune.png`,
    width: 86,
    height: 86,
  },
  rune_lance: {
    src: `${runecasterSkillEffectsPath}/rune_lance.png`,
    width: 88,
    height: 88,
  },
  warding_glyph: {
    src: `${runecasterSkillEffectsPath}/warding_glyph.png`,
    width: 86,
    height: 86,
  },
  rewind_rune: {
    src: `${runecasterSkillEffectsPath}/rewind_rune.png`,
    width: 86,
    height: 86,
  },
  runic_focus: {
    src: `${runecasterSkillEffectsPath}/runic_focus.png`,
    width: 84,
    height: 84,
  },
  leyline_matrix: {
    src: `${runecasterSkillEffectsPath}/leyline_matrix_caster.png`,
    width: 98,
    height: 98,
    targetedSrc: `${runecasterSkillEffectsPath}/leyline_matrix_companion.png`,
    targetedWidth: 60,
    targetedHeight: 60,
  },
  stone_sigil_rhythm: {
    src: `${runecasterSkillEffectsPath}/stone_sigil_rhythm.png`,
    width: 84,
    height: 84,
  },
  rune_step: {
    src: `${runecasterSkillEffectsPath}/rune_step.png`,
    width: 88,
    height: 88,
  },
  blinding_ray: {
    src: `${lightbearerSkillEffectsPath}/blinding_ray.png`,
    width: 86,
    height: 86,
  },
  light_mend: {
    src: `${lightbearerSkillEffectsPath}/light_mend.png`,
    width: 86,
    height: 86,
  },
  sanctuary_veil: {
    src: `${lightbearerSkillEffectsPath}/sanctuary_veil.png`,
    width: 88,
    height: 88,
  },
  guiding_light: {
    src: `${lightbearerSkillEffectsPath}/guiding_light.png`,
    width: 84,
    height: 84,
  },
  radiant_benediction: {
    src: `${lightbearerSkillEffectsPath}/radiant_benediction_caster.png`,
    width: 98,
    height: 98,
    targetedSrc: `${lightbearerSkillEffectsPath}/radiant_benediction_companion.png`,
    targetedWidth: 60,
    targetedHeight: 60,
  },
  herbalist_hymn: {
    src: `${lightbearerSkillEffectsPath}/herbalist_hymn.png`,
    width: 84,
    height: 84,
  },
  dawn_step: {
    src: `${lightbearerSkillEffectsPath}/dawn_step.png`,
    width: 88,
    height: 88,
  },
  circle_of_renewal: {
    src: `${lightbearerSkillEffectsPath}/circle_of_renewal.png`,
    width: 100,
    height: 100,
  },
  whip_prison: {
    src: `${penitentSkillEffectsPath}/whip_prison_caster.png`,
    width: 88,
    height: 88,
    targetedSrc: `${penitentSkillEffectsPath}/whip_prison_target.png`,
    targetedWidth: 88,
    targetedHeight: 88,
    endOpacity: 0.7,
  },
  flagellant_lash: {
    src: `${penitentSkillEffectsPath}/flagellant_lash.png`,
    width: 86,
    height: 86,
  },
  martyrs_veil: {
    src: `${penitentSkillEffectsPath}/martyrs_veil.png`,
    width: 88,
    height: 88,
  },
  penitents_gift: {
    src: `${penitentSkillEffectsPath}/penitents_gift.png`,
    width: 86,
    height: 86,
  },
  eternal_hope: {
    src: `${penitentSkillEffectsPath}/eternal_hope.png`,
    width: 88,
    height: 88,
  },
  burdened_benediction: {
    src: `${penitentSkillEffectsPath}/burdened_benediction_caster.png`,
    width: 98,
    height: 98,
    targetedSrc: `${penitentSkillEffectsPath}/burdened_benediction_companion.png`,
    targetedWidth: 60,
    targetedHeight: 60,
  },
  woodcutting_penance: {
    src: `${penitentSkillEffectsPath}/woodcutting_penance.png`,
    width: 84,
    height: 84,
  },
  atonement_step: {
    src: `${penitentSkillEffectsPath}/atonement_step.png`,
    width: 88,
    height: 88,
  },
};

export const SKILL_VISUAL_PRESENTATION_TEXTURE_SRC = Object.values(
  SKILL_VISUAL_PRESENTATION,
).flatMap((presentation) =>
  presentation
    ? [presentation.src, presentation.targetedSrc].filter(
        (src): src is string => Boolean(src),
      )
    : [],
);

export const SHARED_SKILL_VISUAL_ICON_SRC = {
  projectile: `${beginnerSkillEffectsPath}/generic_projectile.png`,
  slash: `${beginnerSkillEffectsPath}/generic_slash.png`,
  redFlash: `${beginnerSkillEffectsPath}/generic_red_flash.png`,
  heal: `${beginnerSkillEffectsPath}/generic_heal_outline.png`,
} as const;

export const MAP_OBJECT_ICON_SRC = {
  healingFountain: `${beginnerSkillEffectsPath}/hub_healing_fountain.png`,
  teleportBroken: `${teleportAssetPath}/TeleportBroken.png`,
  teleportGood: `${teleportAssetPath}/TeleportGood.png`,
  slimewardTeleportBroken: `${slimewardDungeonAssetPath}/slimeward-teleporter-broken.png`,
  slimewardTeleportGood: `${slimewardDungeonAssetPath}/slimeward-teleporter-active.png`,
  slimewardWaypoint: `${slimewardDungeonAssetPath}/dungeon-waypoint-marker-32.png`,
} as const;

export const SLIMEWARD_DUNGEON_TILE_SRC = {
  floorDamp: `${slimewardDungeonAssetPath}/slimeward-floor-damp-stone-128.png`,
  floorAzure: `${slimewardDungeonAssetPath}/slimeward-floor-azure-slime-stone-128.png`,
  wall: `${slimewardDungeonAssetPath}/slimeward-wall-azure-stone-64.png`,
} as const;
