export type {
  AutonomousEntity,
  BaseEntity,
  ClassDefinition,
  ClassId,
  ClassPath,
  CombatEntity,
  CommandPriority,
  Companion,
  CompanionConsumableBuffs,
  CompanionConsumableBehavior,
  CompanionConsumables,
  CircleOfRenewalTargetMode,
  CompanionSkillBehavior,
  CompanionRole,
  CombatFeedbackEvent,
  CombatFeedbackType,
  CompanionDerivedStats,
  CompanionEquipment,
  CompanionPrimaryStatModifiers,
  CompanionPrimaryStats,
  CompanionGlobalCooldownState,
  DebugMovementResult,
  DebugMapId,
  DebugTeleportPoint,
  HealingFountain,
  DebugTelemetryEntitySnapshot,
  DebugTelemetryEvent,
  DebugTelemetryEventType,
  DebugTelemetryReport,
  DebugTelemetryState,
  DebugTelemetryTick,
  DirectCompanionCommand,
  DirectCompanionCommandResultCode,
  DirectCompanionCommandType,
  AoeCircleShape,
  AoeVisualIntent,
  CompanionAoeAbilityId,
  CompanionAoeChannelState,
  Enemy,
  EnemyAoeAbilityId,
  EnemyAoeChannelPhase,
  EnemyAoeChannelState,
  EnemyAoeCooldownState,
  EnemyAoeInterruptReason,
  EnemyAggressionMode,
  EnemyArchetypeId,
  EnemyTypeDefinition,
  EnemyScalingBand,
  EnemyTypeId,
  EnemyVariant,
  EncounterArea,
  EntityKind,
  EntityState,
  GameEntity,
  GameMap,
  ActiveTeleport,
  LeaderIntent,
  LeaderIntentType,
  LivingEntity,
  PartyBehaviorMode,
  PartyExecutionIntent,
  PartyExecutionIntentType,
  InventoryAddResult,
  InventoryMutationSource,
  InventoryMutationStatus,
  InventoryRemoveResult,
  InventorySlot,
  BankAutoRoutingMode,
  BankSlot,
  BankTransferFailureReason,
  BankTransferResult,
  PartyBank,
  CurrencyDefinition,
  CurrencyId,
  CurrencyMutationResult,
  CurrencyMutationSource,
  CurrencyMutationStatus,
  ConsumableBuffState,
  ConsumableItemId,
  ConsumableKind,
  ConsumableUseSource,
  ConsumableUseState,
  HubDepartureFoodWarningState,
  AccessoryType,
  ActiveCombatProjectile,
  ArmorFamily,
  ArmorType,
  EquipmentItemId,
  EquipmentKind,
  EquipmentSlot,
  EquipmentStatModifiers,
  EquipmentType,
  ItemCategory,
  ItemDefinition,
  ItemId,
  ItemRarity,
  JunkItemId,
  LootTier,
  MapVisualObject,
  MapVisualObjectId,
  OffhandType,
  PartyMemberRole,
  PartyIntent,
  PartyIntentSnapshot,
  PartyIntentSource,
  PartyRecoveryAction,
  PartyRecoveryIntent,
  PartyInventory,
  PartyWallet,
  Position,
  PrimaryStatId,
  NpcEntity,
  ResourceEntity,
  ResourceLocation,
  ResourceItemId,
  ResourceType,
  ResurrectionCancelReason,
  ResurrectionProgressState,
  ResurrectionRecoveryAssignmentState,
  RoleBonusState,
  SkillBindState,
  SkillCooldownState,
  SkillCooldownsBySkillId,
  SkillDamageMitigationState,
  SkillDefinition,
  SkillBookItemId,
  CompanionSkillProgression,
  SkillGatherBuffState,
  SkillId,
  SkillMarkState,
  SkillPartyClassBuffState,
  SkillPartyBuffState,
  SkillSelfBuffState,
  SkillShieldBlockState,
  SkillTag,
  SkillVisualEvent,
  SkillVisualType,
  MobilitySkillUseMode,
  SupportFocus,
  FireBurstTargetMode,
  DropVisualEvent,
  SkillAbsorbShieldState,
  SkillMitigationBuffState,
  DefenseBuffStatusEffect,
  NextAttackDamageBonusStatusEffect,
  PoisonStatusEffect,
  BurningStatusEffect,
  BleedStatusEffect,
  SimpleStatusEffect,
  StatusEffectBase,
  StatusEffectState,
  StatusEffectType,
  WorldWipeRecoveryChoice,
  WorldWipeRecoveryState,
  WeaponType,
  ZoneSubzone,
  ZoneSubzoneBounds,
  ZoneSubzonePassage,
} from "./types";
export type {
  PointOfInterest,
  PoiAvailability,
  PoiCategory,
  PoiMapType,
} from "./poiTypes";
export type {
  GlobalPoiIntent,
  LocalPoiTarget,
  PoiConsideration,
  PoiDecisionState,
  QuestDefinition,
  QuestId,
  QuestObjectiveDefinition,
  QuestObjectiveProgress,
  QuestObjectiveType,
  QuestReward,
  QuestRewardItem,
  QuestSourceType,
  QuestState,
  QuestStatus,
} from "./questTypes";
export type { GameState } from "./state";
export { createInitialGameState } from "./createInitialGameState";
export {
  SAVE_VERSION,
  MAX_OFFLINE_FARMING_MS,
  applyOfflineFarmingProgress,
  createSavedGame,
  restoreGameStateFromSave,
  sanitizeGameStateForSave,
  validateSavedGame,
  type OfflineFarmingResourceSummary,
  type OfflineFarmingSummary,
  type RestoreSaveResult,
  type SavedGame,
  type SaveValidationResult,
} from "./saveGame";

export {
  createCompanion,
  createEnemy,
  createNpc,
  createResource,
  createTargetDummy,
  damageEntity,
  gatherResource,
  isCombatEntity,
  isAutonomousEntity,
  isResourceEntity,
  moveEntityTo,
  moveEntityToward,
  setLastAttackAt,
  setLastGatherAt,
  setEntityState,
  updateAutonomousEntityFollow,
  updateCompanionFollow,
} from "./entities";
export {
  addEnemy,
  addCombatFeedback,
  addEntity,
  addSkillVisualEvent,
  clearExpiredCombatFeedback,
  clearExpiredSkillRuntimeState,
  getEntityById,
  getPoiSearchScope,
  setAutoModeEnabled,
  setCompanionDefendPosition,
  setCompanionRole,
  setPartyLeader,
  setPartyMemberClass,
  setPartyMemberRole,
  setPartyOrder,
  setPoiSearchScope,
  setStayInMapEnabled,
  updateEntity,
  COMPANION_COLLISION_CAPSULE_HEIGHT_MULTIPLIER,
  ENTITY_COLLISION_DISTANCE,
  getEntityCollisionShape,
  isEntitySeparationPositionAvailable,
  isPositionInsideEntityCollisionShape,
  type EntityCollisionShape,
  type PoiSearchScope,
} from "./state";
export {
  ROLE_BONUS_ASSIGNMENT_DELAY_MS,
  assignCurrentRoleBonuses,
  createAssignedRoleBonusState,
  createEmptyRoleBonusState,
  createPendingRoleBonusState,
  getActiveRoleBonusRole,
  getCompanionEffectiveGatherSpeed,
  getCompanionRoleBonusModifiers,
  getRoleBonusDisplayState,
  updateRoleBonusAssignments,
  type CompanionRoleBonusModifiers,
  type RoleBonusDisplayState,
} from "./roleBonus";
export {
  clearPartyIntent,
  getPartyExecutionIntent,
  hasDirectPlayerPartyIntent,
  queuePartyIntent,
  restoreQueuedPartyIntent,
  setLeaderIntent,
  setPartyExecutionIntent,
  setPartyIntent,
  setWorldTravelTargetMapId,
} from "./partyIntentState";
export {
  ITEM_DEFINITIONS,
  getItemDefinition,
  getItemDefinitionForResourceType,
} from "./items";
export {
  ARMOR_FAMILY_LABELS,
  CLASS_EQUIPMENT_PROFILES,
  EQUIPMENT_SLOT_LABELS,
  EQUIPMENT_SLOTS,
  EQUIPMENT_TYPE_LABELS,
  addPrimaryStatModifiers,
  addEquipmentStatModifiers,
  createEmptyCompanionEquipment,
  type ClassEquipmentProfile,
} from "./equipmentTypes";
export {
  BASE_CLASS_AUTOMATIC_STAT_POINTS_PER_LEVEL,
  BASE_CLASS_STAT_GROWTHS,
  BEGINNER_STAT_GROWTH_PER_LEVEL,
  MAX_ALLOCATED_PRIMARY_STAT_POINTS_PER_STAT,
  MINIMUM_ACTUAL_PRIMARY_STAT,
  PLAYER_STAT_POINTS_PER_LEVEL_AFTER_CLASS_UNLOCK,
  PRIMARY_STAT_IDS,
  STARTING_PRIMARY_STAT_VALUE,
  allocateCompanionStatPoint,
  addCompanionPrimaryStats,
  applyCompanionLevelUpStatGrowth,
  createCompanionPrimaryStats,
  createDefaultNaturalCompanionStats,
  createEmptyAllocatedCompanionStats,
  getCompanionActualStats,
  getCompanionActualStatsWithPartyBuffs,
  getCompanionDerivedStats,
  getCompanionDerivedStatsWithPartyBuffs,
  type StatAllocationResult,
  type StatAllocationStatus,
} from "./stats";
export {
  getAllowedEquipmentTypeLabels,
  getCompanionEquipmentPrimaryStatModifiers,
  getCompanionEquipmentStatModifiers,
  getItemsReturnedByEquip,
  isClassAllowedForEquipment,
  isEquipmentSlotCompatible,
  isMainHandOccupyingBothHands,
  validateEquipItem,
  validateEquipmentItemForCompanion,
  validateUnequipItem,
  type EquipmentFailureReason,
  type EquipmentValidationResult,
} from "./equipmentRules";
export {
  equipItemToCompanion,
  unequipItemFromCompanion,
  type EquipmentMutationResult,
  type EquipmentMutationStatus,
} from "./equipmentSystem";
export {
  DEFAULT_AUTO_FLASK_HP_THRESHOLD_PERCENT,
  HUB_DEPARTURE_FOOD_WARNING_DURATION_MS,
  PROTOTYPE_CONSUMABLE_ITEM_IDS,
  PROTOTYPE_FLASK_ITEM_IDS,
  PROTOTYPE_FOOD_ITEM_IDS,
  addHubDepartureFoodWarningIfNeeded,
  assignFoodToCompanion,
  clearExpiredHubDepartureFoodWarning,
  clearExpiredConsumableBuffs,
  createDefaultCompanionConsumableBehavior,
  createEmptyCompanionConsumableBuffs,
  createEmptyCompanionConsumables,
  equipFlaskToCompanion,
  getCompanionFlaskDisplayState,
  getCompanionConsumablePrimaryStatModifiers,
  getCompanionConsumableStatModifiers,
  getConsumableCooldownRemainingMs,
  getHubDepartureFoodWarningCompanionIds,
  isConsumableItemDefinition,
  isFlaskItemDefinition,
  isFoodItemDefinition,
  startCompanionConsumableUse,
  startPartyConsumableUse,
  unequipFlaskFromCompanion,
  updateCompanionConsumableBehavior,
  updateConsumableBehaviorSystem,
  updateConsumableSystem,
  type CompanionFlaskDisplayState,
  type ConsumableBehaviorUpdate,
  type ConsumableMutationResult,
  type ConsumableMutationStatus,
} from "./consumables";
export {
  DEFAULT_BEGINNER_FIRST_AID_ALLY_HEAL_HP_THRESHOLD_PERCENT,
  DEFAULT_BEGINNER_FIRST_AID_SELF_HEAL_HP_THRESHOLD_PERCENT,
  DEFAULT_HOLD_FAST_USE_HP_THRESHOLD_PERCENT,
  DEFAULT_FAKE_DEATH_USE_HP_THRESHOLD_PERCENT,
  DEFAULT_BLOOD_FEAST_USE_HP_THRESHOLD_PERCENT,
  DEFAULT_CIRCLE_OF_RENEWAL_MAIN_TARGET_HP_THRESHOLD_PERCENT,
  DEFAULT_CIRCLE_OF_RENEWAL_TARGET_MODE,
  DEFAULT_DEFENSIVE_MOBILITY_USE_HP_THRESHOLD_PERCENT,
  DEFAULT_FIRE_BURST_TARGET_MODE,
  DEFAULT_MOBILITY_SKILL_USE_MODE,
  DEFAULT_OVERCHARGE_ENABLED,
  DEFAULT_LIGHT_MEND_ALLY_HEAL_HP_THRESHOLD_PERCENT,
  DEFAULT_SECOND_WIND_SELF_HEAL_HP_THRESHOLD_PERCENT,
  DEFAULT_SELF_SACRIFICE_SAFETY_FLOOR_PERCENT,
  DEFAULT_PENITENTS_GIFT_ALLY_HEAL_HP_THRESHOLD_PERCENT,
  DEFAULT_PENITENTS_GIFT_SELF_HEAL_HP_THRESHOLD_PERCENT,
  DEFAULT_ETERNAL_HOPE_USE_HP_THRESHOLD_PERCENT,
  CIRCLE_OF_RENEWAL_MAIN_TARGET_HP_THRESHOLD_MAX_PERCENT,
  DEFENSIVE_MOBILITY_USE_HP_THRESHOLD_MAX_PERCENT,
  HOLD_FAST_USE_HP_THRESHOLD_MAX_PERCENT,
  FAKE_DEATH_USE_HP_THRESHOLD_MAX_PERCENT,
  BLOOD_FEAST_USE_HP_THRESHOLD_MAX_PERCENT,
  LIGHT_MEND_ALLY_HEAL_HP_THRESHOLD_MAX_PERCENT,
  SECOND_WIND_SELF_HEAL_HP_THRESHOLD_MAX_PERCENT,
  SELF_SACRIFICE_SAFETY_FLOOR_MAX_PERCENT,
  PENITENTS_GIFT_ALLY_HEAL_HP_THRESHOLD_MAX_PERCENT,
  PENITENTS_GIFT_SELF_HEAL_HP_THRESHOLD_MAX_PERCENT,
  ETERNAL_HOPE_USE_HP_THRESHOLD_MAX_PERCENT,
  DEFAULT_SUPPORT_FOCUS,
  createDefaultCompanionSkillBehavior,
  getCompanionSkillBehavior,
  updateCompanionSkillBehavior,
  type SkillBehaviorUpdate,
} from "./skillBehavior";
export {
  STARTING_INVENTORY_CAPACITY,
  addItemToInventoryState,
  canStackItems,
  countInventoryItem,
  createEmptyPartyInventory,
  getAvailableInventorySlots,
  getInventorySlotAtIndex,
  getInventorySlotIndex,
  getInventorySlotsByFixedIndex,
  getLockedInventorySlotIndices,
  getUsedInventorySlots,
  isInventorySlotLocked,
  removeItemFromInventorySlotState,
  removeItemFromInventoryState,
  sanitizePartyInventory,
  toggleInventorySlotLock,
} from "./inventory";
export {
  BANK_CAPACITY,
  BANK_INTERACTION_RANGE,
  BANK_MAX_STACK_QUANTITY,
  autoDepositByRoutingMode,
  clampBankTransferQuantity,
  createEmptyPartyBank,
  depositAllToBank,
  depositInventorySlotToBank,
  getBankSlotAtIndex,
  getBankSlotsByFixedIndex,
  getPartyBank,
  isAutoDepositBodyPartDefinition,
  isBankChestNpc,
  isPartyLeaderNearBankChest,
  sanitizeBankAutoRoutingMode,
  sanitizePartyBank,
  setBankAutoRoutingMode,
  toggleBankSlotLock,
  toggleInventoryBankLock,
  withdrawBankSlotToInventory,
  type BankAutoDepositResult,
} from "./bank";
export {
  CURRENCY_DEFINITIONS,
  WALLET_VISIBILITY_DURATION_MS,
  addCurrencyToWalletState,
  canAfford,
  createEmptyPartyWallet,
  formatCurrencyDisplay,
  getCurrencyBalance,
  getCurrencyDefinition,
  markWalletVisible,
  removeCurrencyFromWalletState,
  setCurrencyBalanceForDebug,
} from "./wallet";
export {
  DEFAULT_RESCUE_HUBS,
  WORLD_WIPE_RESCUE_OVERLAY_DURATION_MS,
  getWorldWipeRecoveryChoices,
  resolveWorldWipeRecoveryChoice,
  updateWorldWipeRecovery,
  type RescueHubDefinition,
  type WorldWipeRecoveryOptions,
} from "./worldWipeRecovery";
export {
  buyMerchantItem,
  getFilteredMerchantBuyStock,
  getMerchantBuyStock,
  getMerchantSecondaryFilterOptions,
  getQuickExchangeItemDefinitions,
  getQuickExchangeItems,
  isMerchantNpc,
  isMerchantStockEntryCompatibleWithParty,
  isQuickExchangeItemDefinition,
  quickExchangeParts,
  recordMerchantInteractionClosed,
  recordMerchantInteractionOpened,
  recordMerchantMenuSelected,
  type MerchantBuyFilter,
  type MerchantBuyFailureReason,
  type MerchantBuyResult,
  type MerchantMenuSelection,
  type MerchantSecondaryFilterOption,
  type MerchantStockEntry,
  type MerchantStockFilterOptions,
  type MerchantStockGroup,
  type QuickExchangeItem,
  type QuickExchangeResult,
} from "./merchant";
export {
  CRAFTING_RECIPES,
  SMITH_CRAFTING_INTERACTION_RANGE,
  craftRecipe,
  getCraftingRecipe,
  getCraftingRecipeStatus,
  getCraftingRecipes,
  getSortedCraftingRecipeStatuses,
  isPartyLeaderNearSmith,
  type CraftingCost,
  type CraftingFailureReason,
  type CraftingRecipe,
  type CraftingRecipeId,
  type CraftingRecipeStatus,
  type CraftingRequirementStatus,
  type CraftingResult,
} from "./crafting";
export {
  arePositionsEqual,
  getEuclideanDistance,
  getGridDistance,
  getManhattanDistance,
  getPositionKey,
} from "./positionUtils";
export {
  buildNavigationClickAccessibility,
  getNavigationClickCellKey,
  isNavigationClickAccessible,
  resolveNavigationClickTarget,
  resolveNpcInteractionApproachTarget,
  type NavigationClickAccessibility,
} from "./navigationClick";
export { RESOURCE_INTERACTION_RANGE } from "./resourceInteraction";
export {
  isActiveResource,
  isCompanionEntity,
  isEnemyEntity,
  isLivingCompanion,
  isLivingEnemy,
  isResourceGameEntity,
} from "./entityGuards";
export {
  CLASS_DEFINITIONS,
  FIRST_CLASS_IDS,
  isFirstClassId,
  type FirstClassId,
} from "./classes";
export {
  canCompanionEnterFirstClassSelection,
  selectFirstClass,
  validateFirstClassSelection,
  type FirstClassSelectionFailureReason,
  type FirstClassSelectionResult,
  type FirstClassSelectionValidation,
} from "./classSelection";
export {
  DEFAULT_SKILL_COOLDOWN_MS,
  SKILL_DEFINITIONS,
  getSkillCooldownMs,
  getSkillsForClass,
} from "./skills";
export {
  BEGINNER_SKILL_MAX_RANK,
  CLASS_SKILL_MAX_RANK,
  SKILL_BOOK_ITEM_IDS_BY_SKILL_ID,
  SKILL_RANK_BONUS_PER_RANK,
  canCompanionReadSkillBook,
  createCompanionSkillProgressionForClass,
  ensureCompanionSkillProgressionForClass,
  getActiveSkillsForCompanion,
  getCompanionSkillRank,
  getLegacySkillCandidatesForCompanion,
  getLearnedSkillGroupsForCompanion,
  getScaledSkillDefinitionForCompanion,
  getSkillBookReadCandidates,
  getSkillBookSkillId,
  getSkillMaxRank,
  getSkillRankMultiplier,
  isLegacySkillEnabledForCompanion,
  isLegacySkillEligibleForCompanion,
  isSkillBookItemDefinition,
  readSkillBook,
  sanitizeCompanionSkillProgression,
  sanitizeProgressionForCompanion,
  setCompanionLegacySkillEnabled,
  type ReadSkillBookFailureReason,
  type ReadSkillBookResult,
  type LearnedSkillGroup,
} from "./skillProgression";
export {
  SKILL_ROLE_PREFERENCES,
  getSkillRoleScore,
  type SkillRolePreference,
} from "./skillRolePreferences";
export {
  getOrderedFormationMembers,
  getOrderedPartyMembers,
  getPartyLeader,
  getPartyMembers,
  isGathererBusy,
  isPartyMember,
} from "./partySystem";
export {
  COMBAT_APPROACH_DISTANCE,
  FORMATION_COHESION_PATH_DISTANCE,
  ROLE_PRIORITY,
  ROLE_PROFILES,
  ROLE_TUNING,
  getRolePriority,
} from "./roleProfiles";
export {
  issueEntityCommand,
  issueCompanionCommand,
  issueCompanionCommands,
  issuePartyOrder,
  type CompanionCommand,
  type CompanionGroupCommand,
  type EntityCommand,
  type PartyOrder,
} from "./commands";
export {
  DIRECT_COMMAND_MAX_PATH_DISTANCE,
  DIRECT_COMMAND_REJOIN_GRACE_MS,
  getActiveDirectCompanionCommand,
  getDirectGatherCommandTargetId,
  isCompanionInDirectCommandGrace,
  issueCompanionDirectCommand,
  updateDirectCompanionCommandSystem,
  type CompanionDirectCommandInput,
  type CompanionDirectCommandResult,
} from "./directCompanionCommands";
export { updateGame } from "./updateGame";
export {
  ATTACK_COOLDOWN_MS,
  getAttackCooldownMs,
  updateAttackSystem,
} from "./attackSystem";
export { getDefenseReductionPercent } from "./combatResolver";
export {
  DEFAULT_COMPANION_ATTACK_RANGE,
  getCompanionAttackRange,
} from "./companionCombat";
export {
  ENEMY_DROP_TABLES,
  ENEMY_TYPE_DROP_TABLES,
  SUPPORTED_LOOT_TIERS,
  getEnemyDropTable,
  getEnemyTypeDropTable,
  getLootTierForLevel,
  rollEnemyDropTable,
  type DropGroup,
  type DropRollResult,
  type DropTableEntry,
  type DropTableId,
  type EnemyDropTable,
} from "./dropTables";
export {
  DROP_VISUAL_DURATION_MS,
  handleEnemyDefeatedDrops,
  updateDropSystem,
} from "./dropSystem";
export { updateDefendSystem } from "./defendSystem";
export {
  ENEMY_ARCHETYPES,
  ENEMY_TYPES,
  getEnemyArchetype,
  getEnemyDropArchetypeId,
  getEnemyType,
} from "./enemyArchetypes";
export {
  MAX_ENEMY_SCALING_LEVEL,
  MIN_ENEMY_SCALING_LEVEL,
  getEffectiveEnemyScalingLevel,
  getEnemyCombatStats,
  getEnemyScalingBand,
  getScaledEnemyStats,
  type EnemyCombatStats,
  type EnemyScalingResult,
} from "./enemyScaling";
export {
  getEnemyAggroRange,
  getEnemyAttackLeashDistance,
  getEnemyChaseSpeedMultiplier,
  getEnemyDetectionRange,
  updateEnemyAISystem,
} from "./enemyAISystem";
export {
  ENEMY_RESPAWN_DELAY_MS,
  updateEnemyRespawnSystem,
} from "./enemyRespawnSystem";
export { updateExplorationSystem } from "./explorationSystem";
export { updateGatherSystem } from "./gatherSystem";
export { updateRoleSystem } from "./roleSystem";
export { updateSkillSystem } from "./skillSystem";
export {
  POISON_MAX_DURATION_MULTIPLIER,
  POISON_TICK_INTERVAL_MS,
  applyStatusEffect,
  clearStatusEffectsForEntity,
  consumeForcedEvasionStatus,
  consumeNextAttackDamageBonus,
  dropAggroFromTarget,
  getStatusDefenseBonusPercent,
  isAttackBlockedByStatus,
  isGatherBlockedByStatus,
  isMovementBlockedByStatus,
  isSkillUseBlockedByStatus,
  removeStatusEffects,
  updateStatusEffects,
  type ApplyStatusEffectInput,
  type StatusEffectRemovalFilter,
} from "./statusEffects";
export {
  SHIELD_SHOCKWAVE_CHANNEL_MS,
  updateCompanionAoeChannelSystem,
} from "./companionAoeChannelSystem";
export {
  COMPANION_GLOBAL_COOLDOWN_MS,
  getCompanionGlobalCooldownProgress,
  getCompanionGlobalCooldownRemainingMs,
} from "./companionCooldowns";
export {
  closeSlimewardDungeonChestUi,
  continueSlimewardDungeonChest,
  isSlimewardDungeonChestUiOpen,
  openSlimewardDungeonChest,
  updateSlimewardDungeonSystem,
} from "./dungeonSystem";
export {
  getTeleportWorkingStateById,
  isTeleportWorking,
  setTeleportWorking,
} from "./teleportState";
export {
  isMapTeleportPoiActive,
  isTeleportRallyActive,
  setMapTeleportPoi,
  triggerMapTeleport,
  updateTeleportSystem,
} from "./teleportSystem";
export { updatePoiSystem } from "./poiSystem";
export {
  RESURRECTION_RANGE,
  RESURRECTION_REQUIRED_MS,
  clearResurrectionRecoveryAssignmentForCompanion,
  isCompanionAssignedToResurrectionRecovery,
  isCompanionInActiveResurrectionArea,
  isPositionInActiveResurrectionArea,
  updateResurrectionSystem,
} from "./resurrectionSystem";
export {
  getActivePartyThreatTargetInArea,
  getPartyCombatTarget,
  getPartyMovementTargetPosition,
} from "./partyTargetSystem";
export {
  EQUIPMENT_TUTORIAL_QUEST_ID,
  QUEST_DEFINITIONS,
  QUEST_GIVER_POI_ID,
  QUEST_ORDER,
  acceptQuestFromQuestGiver,
  createInitialQuestStates,
  finishReadyQuestForQuestGiver,
  finishReadyQuestsForQuestGiver,
  getActiveQuest,
  getAvailableQuest,
  getCurrentQuest,
  getFirstIncompleteObjective,
  getQuestGiverAvailableQuests,
  getQuestGiverCurrentQuests,
  getQuestGiverReadyQuests,
  getQuestDefinition,
  getQuestDropItemDisplayName,
  getQuestItemInventoryEntries,
  getQuestTargetMapId,
  hasQuestGiverWork,
  isMerchantUnlockedForQuests,
  recordDungeonChestCollectedForQuests,
  recordEnemyDefeatedForQuests,
  recordEquippedItemObjectivesForQuests,
  recordMerchantEquipmentPurchasedForQuests,
  recordMerchantLockedForQuest,
  recordMapReachedForQuests,
  recordResourceGatheredForQuests,
  updateQuestGiverInteraction,
  type QuestItemInventoryEntry,
} from "./questSystem";
export { startGameLoop, type GameStateUpdater } from "./gameLoop";
export {
  companionIds,
  companionStartPositions,
  classMentorNpcStartData,
  CLASS_MENTOR_NPC_ID,
  createDebugMap,
  debugMapDefinitions,
  DEBUG_MAP_COLUMNS,
  DEBUG_MAP_ROWS,
  aoeTargetDummyId,
  aoeTargetDummyPosition,
  enemyIds,
  getDebugMapDefinition,
  getHubNpcStartDataForQuestState,
  hubHealingFountains,
  hubTwoHealingFountains,
  hubCompanionStartPositions,
  hubNpcStartData,
  HUB_MAP_ID,
  HUB_TWO_MAP_ID,
  HUB_TWO_HEALING_FOUNTAIN_RANGE,
  HUB_TWO_TO_MAP_FOUR_TELEPORTER_ID,
  HUB_TWO_TO_MAP_THREE_TELEPORTER_ID,
  HUB_HEALING_FOUNTAIN_RANGE,
  getHubTwoNpcStartDataForQuestState,
  hubTwoNpcStartData,
  hubTwoCompanionStartPositions,
  MAP_FOUR_TO_HUB_TWO_TELEPORTER_ID,
  mapOneEnemyStartPositions,
  mapOneResourceStartData,
  MAP_ONE_ID,
  MAP_THREE_ID,
  MAP_THREE_TO_HUB_TWO_TELEPORTER_ID,
  MAP_FOUR_ID,
  MAP_TWO_ID,
  resourceIds,
  targetDummyId,
  targetDummyPosition,
  teleporterPosition,
  TELEPORTER_RANGE,
} from "./debugMap";
export {
  AOE_DUMMY_STOMP_ABILITY_ID,
  AOE_DUMMY_STOMP_CHANNEL_MS,
  AOE_DUMMY_STOMP_COOLDOWN_MS,
  AOE_DUMMY_STOMP_DAMAGE,
  AOE_DUMMY_STOMP_RADIUS,
  AOE_DUMMY_STOMP_WINDUP_MS,
  clearEnemyAoeRuntime,
  isEnemyAoeChanneling,
  updateEnemyAoeChannelSystem,
} from "./enemyAoeChannelSystem";
export {
  debugAddCompanion,
  debugAddCompanionToParty,
  debugAddEnemiesToCurrentSubzone,
  debugApplyCompanionInfiniteHealth,
  debugAddPrototypeConsumablesToInventory,
  debugAddPrototypeEquipmentToInventory,
  debugAddTestCrowns,
  debugAddTestWoodToInventory,
  debugFinishCurrentQuest,
  debugForceSuperiorEnemyInCurrentSubzone,
  debugKillOneCompanion,
  debugLevelUpAllCompanions,
  debugRemoveDebugEnemies,
  debugResetSlimewardDungeon,
  debugRefreshResources,
  debugRandomizeLocations,
  debugRemoveCompanion,
  debugRemoveCompanionFromParty,
  debugResurrectEnemy,
  debugRemoveTestCrowns,
  debugResetCrowns,
  debugRestorePartyHealth,
  debugToggleCompanionInfiniteHealth,
  debugToggleCompanionOneHunterClass,
  debugToggleSuperExp,
  debugToggleSuperSpeed,
  debugTurnInCurrentQuest,
} from "./debugTools";
export {
  appendDebugTelemetryEvent,
  clearDebugTelemetry,
  createDebugTelemetryState,
  exportDebugTelemetryReport,
  recordDebugTelemetryTick,
  startDebugTelemetryRecording,
  stopDebugTelemetryRecording,
} from "./debugTelemetry";
export type { CharacterXpProgress } from "./leveling";
export {
  BEGINNER_CLASS_UNLOCK_LEVEL,
  DEBUG_SUPER_EXP_MULTIPLIER,
  MAX_CHARACTER_LEVEL,
  getCharacterXpProgress,
  getCharacterXpToNextLevel,
  getDebugXpMultiplier,
  getEnemyXpReward,
  getLevelGapXpModifier,
  getPartySizeLimit,
  getPartySizeUnlockRequirement,
  getSameLevelEnemyXp,
  getTotalCharacterXpForLevel,
  getTotalPartyCharacterLevel,
  grantCharacterXpToCompanion,
  grantCharacterXpToParty,
  isBeginnerClassEligible,
} from "./leveling";
