import type { ItemDefinition, ItemId, LootTier, ResourceType } from "./types";

export const ITEM_DEFINITIONS: Record<ItemId, ItemDefinition> = {
  wood: {
    id: "wood",
    displayName: "Wood",
    category: "material",
    description: "Legacy prototype gathered wood material.",
    rarity: "common",
    stackable: true,
    maxStack: 250,
  },
  ore: {
    id: "ore",
    displayName: "Ore",
    category: "material",
    description: "Legacy prototype gathered ore material.",
    rarity: "common",
    stackable: true,
    maxStack: 250,
  },
  herb: {
    id: "herb",
    displayName: "Herb",
    category: "material",
    description: "Legacy prototype gathered herb material.",
    rarity: "common",
    stackable: true,
    maxStack: 250,
  },
  softwood: {
    id: "softwood",
    displayName: "Softwood",
    category: "material",
    description: "Tier 1 gathered wood material.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
  },
  copper_ore: {
    id: "copper_ore",
    displayName: "Copper Ore",
    category: "material",
    description: "Tier 1 gathered ore material.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
  },
  field_herb: {
    id: "field_herb",
    displayName: "Field Herb",
    category: "material",
    description: "Tier 1 gathered herb material.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
  },
  hardwood: {
    id: "hardwood",
    displayName: "Hardwood",
    category: "material",
    description: "Tier 2 gathered wood material.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
  },
  iron_ore: {
    id: "iron_ore",
    displayName: "Iron Ore",
    category: "material",
    description: "Tier 2 gathered ore material.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
  },
  redleaf_herb: {
    id: "redleaf_herb",
    displayName: "Redleaf Herb",
    category: "material",
    description: "Tier 2 gathered herb material.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
  },
  slime_gel_t1: {
    id: "slime_gel_t1",
    displayName: "Tier 1 Slime Gel",
    category: "junk",
    description: "Common slime junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 1,
  },
  slime_core_t1: {
    id: "slime_core_t1",
    displayName: "Tier 1 Slime Core",
    category: "junk",
    description: "Rare slime junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 6,
  },
  bat_wing_t1: {
    id: "bat_wing_t1",
    displayName: "Tier 1 Bat Wing",
    category: "junk",
    description: "Common bat junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 2,
  },
  bat_ear_t1: {
    id: "bat_ear_t1",
    displayName: "Tier 1 Bat Ear",
    category: "junk",
    description: "Rare bat junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 8,
  },
  spider_silk_t1: {
    id: "spider_silk_t1",
    displayName: "Tier 1 Spider Silk",
    category: "junk",
    description: "Common spider junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 2,
  },
  spider_fang_t1: {
    id: "spider_fang_t1",
    displayName: "Tier 1 Spider Fang",
    category: "junk",
    description: "Rare spider junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 8,
  },
  goblin_ear_t1: {
    id: "goblin_ear_t1",
    displayName: "Tier 1 Goblin Ear",
    category: "junk",
    description: "Common goblin junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 3,
  },
  goblin_tooth_t1: {
    id: "goblin_tooth_t1",
    displayName: "Tier 1 Goblin Tooth",
    category: "junk",
    description: "Rare goblin junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 10,
  },
  imp_horn_chip_t1: {
    id: "imp_horn_chip_t1",
    displayName: "Tier 1 Imp Horn Chip",
    category: "junk",
    description: "Common imp junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 3,
  },
  imp_tail_t1: {
    id: "imp_tail_t1",
    displayName: "Tier 1 Imp Tail",
    category: "junk",
    description: "Rare imp junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 12,
  },
  wolf_pelt: {
    id: "wolf_pelt",
    displayName: "Tier 1 Wolf Pelt",
    category: "junk",
    description: "Common wolf junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 4,
  },
  wolf_fang: {
    id: "wolf_fang",
    displayName: "Tier 1 Wolf Fang",
    category: "junk",
    description: "Rare wolf junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 14,
  },
  crawler_pebble_t1: {
    id: "crawler_pebble_t1",
    displayName: "Tier 1 Crawler Pebble",
    category: "junk",
    description: "Common crawler junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 4,
  },
  crawler_plate_t1: {
    id: "crawler_plate_t1",
    displayName: "Tier 1 Crawler Plate",
    category: "junk",
    description: "Rare crawler junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 16,
  },
  moss_tuft_t1: {
    id: "moss_tuft_t1",
    displayName: "Tier 1 Moss Tuft",
    category: "junk",
    description: "Common mossling junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 4,
  },
  mossling_cap_t1: {
    id: "mossling_cap_t1",
    displayName: "Tier 1 Mossling Cap",
    category: "junk",
    description: "Rare mossling junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 16,
  },
  goblin_ear_t2: {
    id: "goblin_ear_t2",
    displayName: "Tier 2 Goblin Ear",
    category: "junk",
    description: "Common tier 2 goblin junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 6,
  },
  goblin_tooth_t2: {
    id: "goblin_tooth_t2",
    displayName: "Tier 2 Goblin Tooth",
    category: "junk",
    description: "Rare tier 2 goblin junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 20,
  },
  wisp_ash_t2: {
    id: "wisp_ash_t2",
    displayName: "Tier 2 Wisp Ash",
    category: "junk",
    description: "Common wisp junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 7,
  },
  wisp_ember_t2: {
    id: "wisp_ember_t2",
    displayName: "Tier 2 Wisp Ember",
    category: "junk",
    description: "Rare wisp junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 24,
  },
  orc_hide: {
    id: "orc_hide",
    displayName: "Tier 2 Orc Hide",
    category: "junk",
    description: "Common orc junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 8,
  },
  orc_tusk: {
    id: "orc_tusk",
    displayName: "Tier 2 Orc Tusk",
    category: "junk",
    description: "Rare orc junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 28,
  },
  training_sword: {
    id: "training_sword",
    displayName: "Training Sword",
    category: "equipment",
    description: "Simple starter sword for Beginners.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "training_sword",
    allowedClassIds: ["beginner"],
    statModifiers: { attack: 1 },
  },
  iron_sword: {
    id: "iron_sword",
    displayName: "Iron Sword",
    category: "equipment",
    description: "Prototype one-handed sword for Blades.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "one_handed_sword",
    allowedClassIds: ["blade"],
    statModifiers: { attack: 2 },
  },
  training_mace: {
    id: "training_mace",
    displayName: "Training Mace",
    category: "equipment",
    description: "Prototype one-handed mace for Aegis companions.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "one_handed_mace",
    allowedClassIds: ["aegis"],
    statModifiers: { attack: 1, defense: 1 },
  },
  claw_gauntlets: {
    id: "claw_gauntlets",
    displayName: "Claw Gauntlets",
    category: "equipment",
    description: "Prototype both-hands melee weapon for Beasts.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "claw_gauntlets",
    allowedClassIds: ["beast"],
    statModifiers: { attack: 2, evasion: 1 },
    occupiesBothHands: true,
  },
  thorn_whip: {
    id: "thorn_whip",
    displayName: "Thorn Whip",
    category: "equipment",
    description: "Prototype risky main-hand weapon for Penitents.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "thorn_whip",
    allowedClassIds: ["penitent"],
    statModifiers: { attack: 2, healingPower: 1 },
  },
  short_bow: {
    id: "short_bow",
    displayName: "Short Bow",
    category: "equipment",
    description: "Prototype both-hands weapon for Hunters.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "bow",
    allowedClassIds: ["hunter"],
    statModifiers: { attack: 2 },
    occupiesBothHands: true,
  },
  apprentice_orb: {
    id: "apprentice_orb",
    displayName: "Apprentice Orb",
    category: "equipment",
    description: "Prototype offensive focus for Elementalists.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "orb",
    allowedClassIds: ["elementalist"],
    statModifiers: { magicPower: 2 },
  },
  rune_lantern: {
    id: "rune_lantern",
    displayName: "Rune Lantern",
    category: "equipment",
    description: "Prototype main-hand focus for Runecasters.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "rune_lantern",
    allowedClassIds: ["runecaster"],
    statModifiers: { magicPower: 1, defense: 1 },
  },
  holy_mace: {
    id: "holy_mace",
    displayName: "Holy Mace",
    category: "equipment",
    description: "Prototype main-hand weapon for Lightbearers.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "holy_mace",
    allowedClassIds: ["lightbearer"],
    statModifiers: { attack: 1, healingPower: 1 },
  },
  wooden_shield: {
    id: "wooden_shield",
    displayName: "Wooden Shield",
    category: "equipment",
    description: "Prototype shield for Aegis companions.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "shield",
    allowedClassIds: ["aegis"],
    statModifiers: { defense: 1, block: 1 },
  },
  simple_talisman: {
    id: "simple_talisman",
    displayName: "Simple Talisman",
    category: "equipment",
    description: "Prototype offhand talisman for Runecasters.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "talisman",
    allowedClassIds: ["runecaster"],
    statModifiers: { magicPower: 1 },
  },
  holy_lantern: {
    id: "holy_lantern",
    displayName: "Holy Lantern",
    category: "equipment",
    description: "Prototype offhand lantern for Lightbearers.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "holy_lantern",
    allowedClassIds: ["lightbearer"],
    statModifiers: { healingPower: 2 },
  },
  sacrificial_dagger: {
    id: "sacrificial_dagger",
    displayName: "Sacrificial Dagger",
    category: "equipment",
    description: "Prototype offhand dagger for Penitents.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "sacrificial_dagger",
    allowedClassIds: ["penitent"],
    statModifiers: { attack: 1 },
  },
  cloth_cap: {
    id: "cloth_cap",
    displayName: "Cloth Cap",
    category: "equipment",
    description: "Prototype shared head armor.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    statModifiers: { defense: 1 },
  },
  padded_chest: {
    id: "padded_chest",
    displayName: "Padded Chest",
    category: "equipment",
    description: "Prototype shared chest armor.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    statModifiers: { defense: 2 },
  },
  padded_legs: {
    id: "padded_legs",
    displayName: "Padded Legs",
    category: "equipment",
    description: "Prototype shared leg armor.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    statModifiers: { defense: 1 },
  },
  cloth_gloves: {
    id: "cloth_gloves",
    displayName: "Cloth Gloves",
    category: "equipment",
    description: "Prototype shared gloves.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    statModifiers: { defense: 1 },
  },
  travel_boots: {
    id: "travel_boots",
    displayName: "Travel Boots",
    category: "equipment",
    description: "Prototype shared boots.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    statModifiers: { evasion: 1 },
  },
  plain_charm: {
    id: "plain_charm",
    displayName: "Plain Charm",
    category: "equipment",
    description: "Prototype shared accessory.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "accessory1",
    equipmentKind: "accessory",
    equipmentType: "accessory",
    statModifiers: { maxHealth: 1 },
  },
  worn_cap: {
    id: "worn_cap",
    displayName: "Worn Cap",
    category: "equipment",
    description: "Basic head armor from early enemy drops.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    statModifiers: { defense: 1 },
  },
  worn_tunic: {
    id: "worn_tunic",
    displayName: "Worn Tunic",
    category: "equipment",
    description: "Basic chest armor from early enemy drops.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    statModifiers: { defense: 2 },
  },
  worn_pants: {
    id: "worn_pants",
    displayName: "Worn Pants",
    category: "equipment",
    description: "Basic leg armor from early enemy drops.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    statModifiers: { defense: 2 },
  },
  worn_gloves: {
    id: "worn_gloves",
    displayName: "Worn Gloves",
    category: "equipment",
    description: "Basic gloves from early enemy drops.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    statModifiers: { attack: 1 },
  },
  worn_boots: {
    id: "worn_boots",
    displayName: "Worn Boots",
    category: "equipment",
    description: "Basic boots from early enemy drops.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    statModifiers: { evasion: 1 },
  },
  reinforced_helm: {
    id: "reinforced_helm",
    displayName: "Reinforced Helm",
    category: "equipment",
    description: "Stronger head armor from orc drops.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    statModifiers: { defense: 2 },
  },
  reinforced_armor: {
    id: "reinforced_armor",
    displayName: "Reinforced Armor",
    category: "equipment",
    description: "Stronger chest armor from orc drops.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    statModifiers: { defense: 3 },
  },
  reinforced_legguards: {
    id: "reinforced_legguards",
    displayName: "Reinforced Legguards",
    category: "equipment",
    description: "Stronger leg armor from orc drops.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    statModifiers: { defense: 3 },
  },
  reinforced_gloves: {
    id: "reinforced_gloves",
    displayName: "Reinforced Gloves",
    category: "equipment",
    description: "Stronger gloves from orc drops.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    statModifiers: { attack: 2 },
  },
  reinforced_boots: {
    id: "reinforced_boots",
    displayName: "Reinforced Boots",
    category: "equipment",
    description: "Stronger boots from orc drops.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    statModifiers: { evasion: 2 },
  },
};

export function getItemDefinition(itemId: ItemId): ItemDefinition {
  return ITEM_DEFINITIONS[itemId];
}

export function getItemDefinitionForResourceType(
  resourceType: ResourceType,
  tier: LootTier = 1,
): ItemDefinition {
  return getItemDefinition(getResourceItemId(resourceType, tier));
}

function getResourceItemId(resourceType: ResourceType, tier: LootTier): ItemId {
  if (tier === 2) {
    return resourceType === "wood"
      ? "hardwood"
      : resourceType === "ore"
        ? "iron_ore"
        : "redleaf_herb";
  }

  return resourceType === "wood"
    ? "softwood"
    : resourceType === "ore"
      ? "copper_ore"
      : "field_herb";
}
