import type { ItemDefinition, ItemId, LootTier, ResourceType } from "./types";

export const ITEM_DEFINITIONS: Record<ItemId, ItemDefinition> = {
  wood: {
    id: "wood",
    displayName: "Wood",
    category: "material",
    description: "Legacy prototype gathered wood material.",
    rarity: "common",
    stackable: true,
    maxStack: 250,
  },
  ore: {
    id: "ore",
    displayName: "Ore",
    category: "material",
    description: "Legacy prototype gathered ore material.",
    rarity: "common",
    stackable: true,
    maxStack: 250,
  },
  herb: {
    id: "herb",
    displayName: "Herb",
    category: "material",
    description: "Legacy prototype gathered herb material.",
    rarity: "common",
    stackable: true,
    maxStack: 250,
  },
  softwood: {
    id: "softwood",
    displayName: "Softwood",
    category: "material",
    description: "Tier 1 gathered wood material.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
  },
  copper_ore: {
    id: "copper_ore",
    displayName: "Copper Ore",
    category: "material",
    description: "Tier 1 gathered ore material.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
  },
  field_herb: {
    id: "field_herb",
    displayName: "Field Herb",
    category: "material",
    description: "Tier 1 gathered herb material.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
  },
  hardwood: {
    id: "hardwood",
    displayName: "Hardwood",
    category: "material",
    description: "Tier 2 gathered wood material.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
  },
  iron_ore: {
    id: "iron_ore",
    displayName: "Iron Ore",
    category: "material",
    description: "Tier 2 gathered ore material.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
  },
  redleaf_herb: {
    id: "redleaf_herb",
    displayName: "Redleaf Herb",
    category: "material",
    description: "Tier 2 gathered herb material.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
  },
  minor_recovery_flask: {
    id: "minor_recovery_flask",
    displayName: "Minor Recovery Flask",
    category: "consumable",
    description: "Prototype flask. Heals 50% max HP after a short use.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    consumableKind: "flask",
    useDurationMs: 2000,
    cooldownMs: 20000,
    maxCharges: 100,
    chargeCost: 1,
    healPercent: 0.5,
    levelRequirement: 1,
  },
  soldiers_recovery_flask: {
    id: "soldiers_recovery_flask",
    displayName: "Soldier's Recovery Flask",
    category: "consumable",
    description: "Prototype flask. Heals 25% max HP and grants +1 Attack.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    consumableKind: "flask",
    useDurationMs: 2000,
    cooldownMs: 30000,
    maxCharges: 100,
    chargeCost: 1,
    healPercent: 0.25,
    buffDurationMs: 30000,
    statModifiers: {
      attack: 1,
    },
    levelRequirement: 1,
  },
  hearty_trail_rations: {
    id: "hearty_trail_rations",
    displayName: "Hearty Trail Rations",
    category: "consumable",
    description: "Prototype food. Grants Strength and Constitution.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    consumableKind: "food",
    useDurationMs: 5000,
    buffDurationMs: 600000,
    primaryStatModifiers: {
      strength: 1,
      constitution: 1,
    },
    levelRequirement: 5,
  },
  skirmisher_rations: {
    id: "skirmisher_rations",
    displayName: "Skirmisher Rations",
    category: "consumable",
    description: "Prototype food. Grants Strength and Dexterity.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    consumableKind: "food",
    useDurationMs: 5000,
    buffDurationMs: 600000,
    primaryStatModifiers: {
      strength: 1,
      dexterity: 1,
    },
    levelRequirement: 5,
  },
  throw_rock_skill_book: {
    id: "throw_rock_skill_book",
    displayName: "Throw Rock Skill Book",
    category: "skill_book",
    description: "A training book that raises Throw Rock by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "throw_rock",
  },
  kick_skill_book: {
    id: "kick_skill_book",
    displayName: "Kick Skill Book",
    category: "skill_book",
    description: "A training book that raises Kick by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "kick",
  },
  guard_up_skill_book: {
    id: "guard_up_skill_book",
    displayName: "Guard Up Skill Book",
    category: "skill_book",
    description: "A training book that raises Guard Up by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "guard_up",
  },
  first_aid_skill_book: {
    id: "first_aid_skill_book",
    displayName: "First Aid Skill Book",
    category: "skill_book",
    description: "A training book that raises First Aid by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "first_aid",
  },
  deep_breath_skill_book: {
    id: "deep_breath_skill_book",
    displayName: "Deep Breath Skill Book",
    category: "skill_book",
    description: "A training book that raises Deep Breath by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "deep_breath",
  },
  rally_call_skill_book: {
    id: "rally_call_skill_book",
    displayName: "Rally Call Skill Book",
    category: "skill_book",
    description: "A training book that raises Rally Call by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "rally_call",
  },
  field_hands_skill_book: {
    id: "field_hands_skill_book",
    displayName: "Field Hands Skill Book",
    category: "skill_book",
    description: "A training book that raises Field Hands by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "field_hands",
  },
  quick_step_skill_book: {
    id: "quick_step_skill_book",
    displayName: "Quick Step Skill Book",
    category: "skill_book",
    description: "A training book that raises Quick Step by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "quick_step",
  },
  duelist_challenge_skill_book: {
    id: "duelist_challenge_skill_book",
    displayName: "Duelist Challenge Skill Book",
    category: "skill_book",
    description: "A training book that raises Duelist Challenge by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "duelist_challenge",
  },
  second_wind_skill_book: {
    id: "second_wind_skill_book",
    displayName: "Second Wind Skill Book",
    category: "skill_book",
    description: "A training book that raises Second Wind by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "second_wind",
  },
  blade_parry_skill_book: {
    id: "blade_parry_skill_book",
    displayName: "Blade Parry Skill Book",
    category: "skill_book",
    description: "A training book that raises Blade Parry by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "blade_parry",
  },
  edge_focus_skill_book: {
    id: "edge_focus_skill_book",
    displayName: "Edge Focus Skill Book",
    category: "skill_book",
    description: "A training book that raises Edge Focus by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "edge_focus",
  },
  press_the_opening_skill_book: {
    id: "press_the_opening_skill_book",
    displayName: "Press the Opening Skill Book",
    category: "skill_book",
    description: "A training book that raises Press the Opening by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "press_the_opening",
  },
  woodcutter_rhythm_skill_book: {
    id: "woodcutter_rhythm_skill_book",
    displayName: "Woodcutter Rhythm Skill Book",
    category: "skill_book",
    description: "A training book that raises Woodcutter Rhythm by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "woodcutter_rhythm",
  },
  flash_step_skill_book: {
    id: "flash_step_skill_book",
    displayName: "Flash Step Skill Book",
    category: "skill_book",
    description: "A training book that raises Flash Step by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "flash_step",
  },
  sweeping_strike_skill_book: {
    id: "sweeping_strike_skill_book",
    displayName: "Sweeping Strike Skill Book",
    category: "skill_book",
    description: "A training book that raises Sweeping Strike by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "sweeping_strike",
  },
  shield_challenge_skill_book: {
    id: "shield_challenge_skill_book",
    displayName: "Shield Challenge Skill Book",
    category: "skill_book",
    description: "A training book that raises Shield Challenge by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "shield_challenge",
  },
  hold_fast_skill_book: {
    id: "hold_fast_skill_book",
    displayName: "Hold Fast Skill Book",
    category: "skill_book",
    description: "A training book that raises Hold Fast by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "hold_fast",
  },
  guard_wall_skill_book: {
    id: "guard_wall_skill_book",
    displayName: "Guard Wall Skill Book",
    category: "skill_book",
    description: "A training book that raises Guard Wall by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "guard_wall",
  },
  iron_stance_skill_book: {
    id: "iron_stance_skill_book",
    displayName: "Iron Stance Skill Book",
    category: "skill_book",
    description: "A training book that raises Iron Stance by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "iron_stance",
  },
  shield_formation_skill_book: {
    id: "shield_formation_skill_book",
    displayName: "Shield Formation Skill Book",
    category: "skill_book",
    description: "A training book that raises Shield Formation by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "shield_formation",
  },
  stonebreaker_rhythm_skill_book: {
    id: "stonebreaker_rhythm_skill_book",
    displayName: "Stonebreaker Rhythm Skill Book",
    category: "skill_book",
    description: "A training book that raises Stonebreaker Rhythm by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "stonebreaker_rhythm",
  },
  shield_rush_skill_book: {
    id: "shield_rush_skill_book",
    displayName: "Shield Rush Skill Book",
    category: "skill_book",
    description: "A training book that raises Shield Rush by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "shield_rush",
  },
  shield_shockwave_skill_book: {
    id: "shield_shockwave_skill_book",
    displayName: "Shield Shockwave Skill Book",
    category: "skill_book",
    description: "A training book that raises Shield Shockwave by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "shield_shockwave",
  },
  pinning_shot_skill_book: {
    id: "pinning_shot_skill_book",
    displayName: "Pinning Shot Skill Book",
    category: "skill_book",
    description: "A training book that raises Pinning Shot by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "pinning_shot",
  },
  fake_death_skill_book: {
    id: "fake_death_skill_book",
    displayName: "Fake Death Skill Book",
    category: "skill_book",
    description: "A training book that raises Fake Death by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "fake_death",
  },
  evasive_instinct_skill_book: {
    id: "evasive_instinct_skill_book",
    displayName: "Evasive Instinct Skill Book",
    category: "skill_book",
    description: "A training book that raises Evasive Instinct by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "evasive_instinct",
  },
  hunters_focus_skill_book: {
    id: "hunters_focus_skill_book",
    displayName: "Hunter's Focus Skill Book",
    category: "skill_book",
    description: "A training book that raises Hunter's Focus by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "hunters_focus",
  },
  poison_coating_skill_book: {
    id: "poison_coating_skill_book",
    displayName: "Poison Coating Skill Book",
    category: "skill_book",
    description: "A training book that raises Poison Coating by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "poison_coating",
  },
  herbalist_rhythm_skill_book: {
    id: "herbalist_rhythm_skill_book",
    displayName: "Herbalist Rhythm Skill Book",
    category: "skill_book",
    description: "A training book that raises Herbalist Rhythm by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "herbalist_rhythm",
  },
  skirmish_shot_skill_book: {
    id: "skirmish_shot_skill_book",
    displayName: "Skirmish Shot Skill Book",
    category: "skill_book",
    description: "A training book that raises Skirmish Shot by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "skirmish_shot",
  },
  arrow_burst_skill_book: {
    id: "arrow_burst_skill_book",
    displayName: "Arrow Burst Skill Book",
    category: "skill_book",
    description: "A training book that raises Arrow Burst by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "arrow_burst",
  },
  threatening_roar_skill_book: {
    id: "threatening_roar_skill_book",
    displayName: "Threatening Roar Skill Book",
    category: "skill_book",
    description: "A training book that raises Threatening Roar by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "threatening_roar",
  },
  blood_feast_skill_book: {
    id: "blood_feast_skill_book",
    displayName: "Blood Feast Skill Book",
    category: "skill_book",
    description: "A training book that raises Blood Feast by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "blood_feast",
  },
  rugged_hide_skill_book: {
    id: "rugged_hide_skill_book",
    displayName: "Rugged Hide Skill Book",
    category: "skill_book",
    description: "A training book that raises Rugged Hide by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "rugged_hide",
  },
  feral_surge_skill_book: {
    id: "feral_surge_skill_book",
    displayName: "Feral Surge Skill Book",
    category: "skill_book",
    description: "A training book that raises Feral Surge by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "feral_surge",
  },
  pack_frenzy_skill_book: {
    id: "pack_frenzy_skill_book",
    displayName: "Pack Frenzy Skill Book",
    category: "skill_book",
    description: "A training book that raises Pack Frenzy by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "pack_frenzy",
  },
  stoneclaw_rhythm_skill_book: {
    id: "stoneclaw_rhythm_skill_book",
    displayName: "Stoneclaw Rhythm Skill Book",
    category: "skill_book",
    description: "A training book that raises Stoneclaw Rhythm by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "stoneclaw_rhythm",
  },
  pounce_skill_book: {
    id: "pounce_skill_book",
    displayName: "Pounce Skill Book",
    category: "skill_book",
    description: "A training book that raises Pounce by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "pounce",
  },
  maul_sweep_skill_book: {
    id: "maul_sweep_skill_book",
    displayName: "Maul Sweep Skill Book",
    category: "skill_book",
    description: "A training book that raises Maul Sweep by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "maul_sweep",
  },
  elemental_bolt_skill_book: {
    id: "elemental_bolt_skill_book",
    displayName: "Elemental Bolt Skill Book",
    category: "skill_book",
    description: "A training book that raises Elemental Bolt by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "elemental_bolt",
  },
  mana_shield_skill_book: {
    id: "mana_shield_skill_book",
    displayName: "Mana Shield Skill Book",
    category: "skill_book",
    description: "A training book that raises Mana Shield by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "mana_shield",
  },
  frost_armor_skill_book: {
    id: "frost_armor_skill_book",
    displayName: "Frost Armor Skill Book",
    category: "skill_book",
    description: "A training book that raises Frost Armor by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "frost_armor",
  },
  overcharge_skill_book: {
    id: "overcharge_skill_book",
    displayName: "Overcharge Skill Book",
    category: "skill_book",
    description: "A training book that raises Overcharge by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "overcharge",
  },
  arcane_conduit_skill_book: {
    id: "arcane_conduit_skill_book",
    displayName: "Arcane Conduit Skill Book",
    category: "skill_book",
    description: "A training book that raises Arcane Conduit by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "arcane_conduit",
  },
  emberwood_rhythm_skill_book: {
    id: "emberwood_rhythm_skill_book",
    displayName: "Emberwood Rhythm Skill Book",
    category: "skill_book",
    description: "A training book that raises Emberwood Rhythm by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "emberwood_rhythm",
  },
  flame_step_skill_book: {
    id: "flame_step_skill_book",
    displayName: "Flame Step Skill Book",
    category: "skill_book",
    description: "A training book that raises Flame Step by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "flame_step",
  },
  fire_burst_skill_book: {
    id: "fire_burst_skill_book",
    displayName: "FireBurst Skill Book",
    category: "skill_book",
    description: "A training book that raises FireBurst by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "fire_burst",
  },
  binding_rune_skill_book: {
    id: "binding_rune_skill_book",
    displayName: "Binding Rune Skill Book",
    category: "skill_book",
    description: "A training book that raises Binding Rune by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "binding_rune",
  },
  rune_lance_skill_book: {
    id: "rune_lance_skill_book",
    displayName: "Rune Lance Skill Book",
    category: "skill_book",
    description: "A training book that raises Rune Lance by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "rune_lance",
  },
  warding_glyph_skill_book: {
    id: "warding_glyph_skill_book",
    displayName: "Warding Glyph Skill Book",
    category: "skill_book",
    description: "A training book that raises Warding Glyph by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "warding_glyph",
  },
  rewind_rune_skill_book: {
    id: "rewind_rune_skill_book",
    displayName: "Rewind Rune Skill Book",
    category: "skill_book",
    description: "A training book that raises Rewind Rune by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "rewind_rune",
  },
  runic_focus_skill_book: {
    id: "runic_focus_skill_book",
    displayName: "Runic Focus Skill Book",
    category: "skill_book",
    description: "A training book that raises Runic Focus by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "runic_focus",
  },
  leyline_matrix_skill_book: {
    id: "leyline_matrix_skill_book",
    displayName: "Leyline Matrix Skill Book",
    category: "skill_book",
    description: "A training book that raises Leyline Matrix by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "leyline_matrix",
  },
  stone_sigil_rhythm_skill_book: {
    id: "stone_sigil_rhythm_skill_book",
    displayName: "Stone Sigil Rhythm Skill Book",
    category: "skill_book",
    description: "A training book that raises Stone Sigil Rhythm by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "stone_sigil_rhythm",
  },
  rune_step_skill_book: {
    id: "rune_step_skill_book",
    displayName: "Rune Step Skill Book",
    category: "skill_book",
    description: "A training book that raises Rune Step by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "rune_step",
  },
  blinding_ray_skill_book: {
    id: "blinding_ray_skill_book",
    displayName: "Blinding Ray Skill Book",
    category: "skill_book",
    description: "A training book that raises Blinding Ray by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "blinding_ray",
  },
  light_mend_skill_book: {
    id: "light_mend_skill_book",
    displayName: "Light Mend Skill Book",
    category: "skill_book",
    description: "A training book that raises Light Mend by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "light_mend",
  },
  sanctuary_veil_skill_book: {
    id: "sanctuary_veil_skill_book",
    displayName: "Sanctuary Veil Skill Book",
    category: "skill_book",
    description: "A training book that raises Sanctuary Veil by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "sanctuary_veil",
  },
  guiding_light_skill_book: {
    id: "guiding_light_skill_book",
    displayName: "Guiding Light Skill Book",
    category: "skill_book",
    description: "A training book that raises Guiding Light by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "guiding_light",
  },
  radiant_benediction_skill_book: {
    id: "radiant_benediction_skill_book",
    displayName: "Radiant Benediction Skill Book",
    category: "skill_book",
    description: "A training book that raises Radiant Benediction by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "radiant_benediction",
  },
  herbalist_hymn_skill_book: {
    id: "herbalist_hymn_skill_book",
    displayName: "Herbalist Hymn Skill Book",
    category: "skill_book",
    description: "A training book that raises Herbalist Hymn by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "herbalist_hymn",
  },
  dawn_step_skill_book: {
    id: "dawn_step_skill_book",
    displayName: "Dawn Step Skill Book",
    category: "skill_book",
    description: "A training book that raises Dawn Step by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "dawn_step",
  },
  circle_of_renewal_skill_book: {
    id: "circle_of_renewal_skill_book",
    displayName: "Circle of Renewal Skill Book",
    category: "skill_book",
    description: "A training book that raises Circle of Renewal by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "circle_of_renewal",
  },
  penitents_gift_skill_book: {
    id: "penitents_gift_skill_book",
    displayName: "Penitent's Gift Skill Book",
    category: "skill_book",
    description: "A training book that raises Penitent's Gift by one rank.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 99,
    skillBookSkillId: "penitents_gift",
  },
  slime_gel_t1: {
    id: "slime_gel_t1",
    displayName: "Tier 1 Slime Gel",
    category: "junk",
    description: "Common slime junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 1,
  },
  slime_core_t1: {
    id: "slime_core_t1",
    displayName: "Tier 1 Slime Core",
    category: "junk",
    description: "Rare slime junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 6,
  },
  bat_wing_t1: {
    id: "bat_wing_t1",
    displayName: "Tier 1 Bat Wing",
    category: "junk",
    description: "Common bat junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 2,
  },
  bat_ear_t1: {
    id: "bat_ear_t1",
    displayName: "Tier 1 Bat Ear",
    category: "junk",
    description: "Rare bat junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 8,
  },
  spider_silk_t1: {
    id: "spider_silk_t1",
    displayName: "Tier 1 Spider Silk",
    category: "junk",
    description: "Common spider junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 2,
  },
  spider_fang_t1: {
    id: "spider_fang_t1",
    displayName: "Tier 1 Spider Fang",
    category: "junk",
    description: "Rare spider junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 8,
  },
  goblin_ear_t1: {
    id: "goblin_ear_t1",
    displayName: "Tier 1 Goblin Ear",
    category: "junk",
    description: "Common goblin junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 3,
  },
  goblin_tooth_t1: {
    id: "goblin_tooth_t1",
    displayName: "Tier 1 Goblin Tooth",
    category: "junk",
    description: "Rare goblin junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 10,
  },
  imp_horn_chip_t1: {
    id: "imp_horn_chip_t1",
    displayName: "Tier 1 Imp Horn Chip",
    category: "junk",
    description: "Common imp junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 3,
  },
  imp_tail_t1: {
    id: "imp_tail_t1",
    displayName: "Tier 1 Imp Tail",
    category: "junk",
    description: "Rare imp junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 12,
  },
  wolf_pelt: {
    id: "wolf_pelt",
    displayName: "Tier 1 Wolf Pelt",
    category: "junk",
    description: "Common wolf junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 4,
  },
  wolf_fang: {
    id: "wolf_fang",
    displayName: "Tier 1 Wolf Fang",
    category: "junk",
    description: "Rare wolf junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 14,
  },
  crawler_pebble_t1: {
    id: "crawler_pebble_t1",
    displayName: "Tier 1 Crawler Pebble",
    category: "junk",
    description: "Common crawler junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 4,
  },
  crawler_plate_t1: {
    id: "crawler_plate_t1",
    displayName: "Tier 1 Crawler Plate",
    category: "junk",
    description: "Rare crawler junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 16,
  },
  moss_tuft_t1: {
    id: "moss_tuft_t1",
    displayName: "Tier 1 Moss Tuft",
    category: "junk",
    description: "Common mossling junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 4,
  },
  mossling_cap_t1: {
    id: "mossling_cap_t1",
    displayName: "Tier 1 Mossling Cap",
    category: "junk",
    description: "Rare mossling junk for quick exchange.",
    rarity: "common",
    tier: 1,
    stackable: true,
    maxStack: 250,
    sellValue: 16,
  },
  goblin_ear_t2: {
    id: "goblin_ear_t2",
    displayName: "Tier 2 Goblin Ear",
    category: "junk",
    description: "Common tier 2 goblin junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 6,
  },
  goblin_tooth_t2: {
    id: "goblin_tooth_t2",
    displayName: "Tier 2 Goblin Tooth",
    category: "junk",
    description: "Rare tier 2 goblin junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 20,
  },
  wisp_ash_t2: {
    id: "wisp_ash_t2",
    displayName: "Tier 2 Wisp Ash",
    category: "junk",
    description: "Common wisp junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 7,
  },
  wisp_ember_t2: {
    id: "wisp_ember_t2",
    displayName: "Tier 2 Wisp Ember",
    category: "junk",
    description: "Rare wisp junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 24,
  },
  orc_hide: {
    id: "orc_hide",
    displayName: "Tier 2 Orc Hide",
    category: "junk",
    description: "Common orc junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 8,
  },
  orc_tusk: {
    id: "orc_tusk",
    displayName: "Tier 2 Orc Tusk",
    category: "junk",
    description: "Rare orc junk for quick exchange.",
    rarity: "common",
    tier: 2,
    stackable: true,
    maxStack: 250,
    sellValue: 28,
  },
  training_sword: {
    id: "training_sword",
    displayName: "Training Sword",
    category: "equipment",
    description: "Simple starter sword for Beginners.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "training_sword",
    allowedClassIds: ["beginner"],
    statModifiers: { attack: 1 },
    levelRequirement: 1,
  },
  iron_sword: {
    id: "iron_sword",
    displayName: "Iron Sword",
    category: "equipment",
    description: "Prototype one-handed sword for Blades.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "one_handed_sword",
    allowedClassIds: ["blade"],
    statModifiers: { attack: 2 },
    levelRequirement: 10,
  },
  guard_mace: {
    id: "guard_mace",
    displayName: "Guard Mace",
    category: "equipment",
    description: "Prototype one-handed mace for Aegis companions.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "one_handed_mace",
    allowedClassIds: ["aegis"],
    statModifiers: { attack: 1, defense: 1 },
    levelRequirement: 10,
  },
  claw_gauntlets: {
    id: "claw_gauntlets",
    displayName: "Claw Gauntlets",
    category: "equipment",
    description: "Prototype both-hands melee weapon for Beasts.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "claw_gauntlets",
    allowedClassIds: ["beast"],
    statModifiers: { attack: 2, evasion: 1 },
    levelRequirement: 10,
    occupiesBothHands: true,
  },
  thorn_whip: {
    id: "thorn_whip",
    displayName: "Thorn Whip",
    category: "equipment",
    description: "Prototype risky main-hand weapon for Penitents.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "thorn_whip",
    allowedClassIds: ["penitent"],
    statModifiers: { attack: 2, healingPower: 1 },
    levelRequirement: 10,
  },
  short_bow: {
    id: "short_bow",
    displayName: "Short Bow",
    category: "equipment",
    description: "Prototype both-hands weapon for Hunters.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "bow",
    allowedClassIds: ["hunter"],
    statModifiers: { attack: 2 },
    levelRequirement: 10,
    occupiesBothHands: true,
  },
  apprentice_orb: {
    id: "apprentice_orb",
    displayName: "Apprentice Orb",
    category: "equipment",
    description: "Prototype offensive focus for Elementalists.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "orb",
    allowedClassIds: ["elementalist"],
    statModifiers: { magicPower: 2 },
    levelRequirement: 10,
  },
  rune_lantern: {
    id: "rune_lantern",
    displayName: "Rune Lantern",
    category: "equipment",
    description: "Prototype main-hand focus for Runecasters.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "rune_lantern",
    allowedClassIds: ["runecaster"],
    statModifiers: { magicPower: 1, defense: 1 },
    levelRequirement: 10,
  },
  holy_mace: {
    id: "holy_mace",
    displayName: "Holy Mace",
    category: "equipment",
    description: "Prototype main-hand weapon for Lightbearers.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "holy_mace",
    allowedClassIds: ["lightbearer"],
    statModifiers: { attack: 1, healingPower: 1 },
    levelRequirement: 10,
  },
  wooden_shield: {
    id: "wooden_shield",
    displayName: "Wooden Shield",
    category: "equipment",
    description: "Prototype shield for Aegis companions.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "shield",
    allowedClassIds: ["aegis"],
    statModifiers: { defense: 1, block: 1 },
    levelRequirement: 10,
  },
  simple_talisman: {
    id: "simple_talisman",
    displayName: "Simple Talisman",
    category: "equipment",
    description: "Prototype offhand talisman for Runecasters.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "talisman",
    allowedClassIds: ["runecaster"],
    statModifiers: { magicPower: 1 },
    levelRequirement: 10,
  },
  holy_lantern: {
    id: "holy_lantern",
    displayName: "Holy Lantern",
    category: "equipment",
    description: "Prototype offhand lantern for Lightbearers.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "holy_lantern",
    allowedClassIds: ["lightbearer"],
    statModifiers: { healingPower: 2 },
    levelRequirement: 10,
  },
  sacrificial_dagger: {
    id: "sacrificial_dagger",
    displayName: "Sacrificial Dagger",
    category: "equipment",
    description: "Prototype offhand dagger for Penitents.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "sacrificial_dagger",
    allowedClassIds: ["penitent"],
    statModifiers: { attack: 1 },
    levelRequirement: 10,
  },
  acolyte_hood: {
    id: "acolyte_hood",
    displayName: "Acolyte Hood",
    category: "equipment",
    description: "Tier 1 healing-focused cloth head armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    armorFamily: "cloth",
    primaryStatModifiers: { wisdom: 1 },
    statModifiers: { healingPower: 1 },
    levelRequirement: 10,
  },
  acolyte_robe: {
    id: "acolyte_robe",
    displayName: "Acolyte Robe",
    category: "equipment",
    description: "Tier 1 healing-focused cloth chest armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    armorFamily: "cloth",
    primaryStatModifiers: { wisdom: 1 },
    statModifiers: { healingPower: 2, magicDefense: 1 },
    levelRequirement: 10,
  },
  acolyte_pants: {
    id: "acolyte_pants",
    displayName: "Acolyte Pants",
    category: "equipment",
    description: "Tier 1 stabilizing cloth leg armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    armorFamily: "cloth",
    primaryStatModifiers: { constitution: 1 },
    statModifiers: { magicDefense: 1 },
    levelRequirement: 10,
  },
  acolyte_wraps: {
    id: "acolyte_wraps",
    displayName: "Acolyte Wraps",
    category: "equipment",
    description: "Tier 1 healing-focused cloth gloves.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    armorFamily: "cloth",
    primaryStatModifiers: { wisdom: 1 },
    statModifiers: { healingPower: 1 },
    levelRequirement: 10,
  },
  acolyte_sandals: {
    id: "acolyte_sandals",
    displayName: "Acolyte Sandals",
    category: "equipment",
    description: "Tier 1 protective cloth boots.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    armorFamily: "cloth",
    statModifiers: { evasion: 1, magicDefense: 1 },
    levelRequirement: 10,
  },
  scholar_hood: {
    id: "scholar_hood",
    displayName: "Scholar Hood",
    category: "equipment",
    description: "Tier 1 magic-focused cloth head armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    armorFamily: "cloth",
    primaryStatModifiers: { intelligence: 1 },
    statModifiers: { magicPower: 1 },
    levelRequirement: 10,
  },
  scholar_robe: {
    id: "scholar_robe",
    displayName: "Scholar Robe",
    category: "equipment",
    description: "Tier 1 magic-focused cloth chest armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    armorFamily: "cloth",
    primaryStatModifiers: { intelligence: 1 },
    statModifiers: { magicPower: 2, magicDefense: 1 },
    levelRequirement: 10,
  },
  scholar_pants: {
    id: "scholar_pants",
    displayName: "Scholar Pants",
    category: "equipment",
    description: "Tier 1 magic-focused cloth leg armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    armorFamily: "cloth",
    primaryStatModifiers: { intelligence: 1 },
    statModifiers: { magicDefense: 1 },
    levelRequirement: 10,
  },
  scholar_gloves: {
    id: "scholar_gloves",
    displayName: "Scholar Gloves",
    category: "equipment",
    description: "Tier 1 precise casting cloth gloves.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    armorFamily: "cloth",
    statModifiers: { magicPower: 1, accuracy: 1 },
    levelRequirement: 10,
  },
  scholar_sandals: {
    id: "scholar_sandals",
    displayName: "Scholar Sandals",
    category: "equipment",
    description: "Tier 1 mobile casting cloth boots.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    armorFamily: "cloth",
    statModifiers: { evasion: 1, magicPower: 1 },
    levelRequirement: 10,
  },
  scout_cap: {
    id: "scout_cap",
    displayName: "Scout Cap",
    category: "equipment",
    description: "Tier 1 evasive leather head armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    armorFamily: "leather",
    primaryStatModifiers: { dexterity: 1 },
    statModifiers: { evasion: 1 },
    levelRequirement: 1,
  },
  scout_jacket: {
    id: "scout_jacket",
    displayName: "Scout Jacket",
    category: "equipment",
    description: "Tier 1 evasive leather chest armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    armorFamily: "leather",
    primaryStatModifiers: { dexterity: 1 },
    statModifiers: { defense: 1, evasion: 1 },
    levelRequirement: 1,
  },
  scout_trousers: {
    id: "scout_trousers",
    displayName: "Scout Trousers",
    category: "equipment",
    description: "Tier 1 evasive leather leg armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    armorFamily: "leather",
    primaryStatModifiers: { dexterity: 1 },
    statModifiers: { evasion: 1 },
    levelRequirement: 1,
  },
  scout_gloves: {
    id: "scout_gloves",
    displayName: "Scout Gloves",
    category: "equipment",
    description: "Tier 1 precise leather gloves.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    armorFamily: "leather",
    primaryStatModifiers: { dexterity: 1 },
    statModifiers: { accuracy: 1 },
    levelRequirement: 1,
  },
  scout_boots: {
    id: "scout_boots",
    displayName: "Scout Boots",
    category: "equipment",
    description: "Tier 1 evasive leather boots.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    armorFamily: "leather",
    statModifiers: { evasion: 2 },
    levelRequirement: 1,
  },
  stalker_mask: {
    id: "stalker_mask",
    displayName: "Stalker Mask",
    category: "equipment",
    description: "Tier 1 aggressive leather head armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    armorFamily: "leather",
    primaryStatModifiers: { dexterity: 1 },
    statModifiers: { attack: 1 },
    levelRequirement: 5,
  },
  stalker_vest: {
    id: "stalker_vest",
    displayName: "Stalker Vest",
    category: "equipment",
    description: "Tier 1 aggressive leather chest armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    armorFamily: "leather",
    statModifiers: { attack: 1, defense: 1, evasion: 1 },
    levelRequirement: 5,
  },
  stalker_leggings: {
    id: "stalker_leggings",
    displayName: "Stalker Leggings",
    category: "equipment",
    description: "Tier 1 aggressive leather leg armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    armorFamily: "leather",
    primaryStatModifiers: { strength: 1 },
    statModifiers: { evasion: 1 },
    levelRequirement: 5,
  },
  stalker_grips: {
    id: "stalker_grips",
    displayName: "Stalker Grips",
    category: "equipment",
    description: "Tier 1 aggressive leather gloves.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    armorFamily: "leather",
    statModifiers: { attack: 1, criticalChance: 0.02 },
    levelRequirement: 5,
  },
  stalker_boots: {
    id: "stalker_boots",
    displayName: "Stalker Boots",
    category: "equipment",
    description: "Tier 1 aggressive leather boots.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    armorFamily: "leather",
    primaryStatModifiers: { dexterity: 1 },
    statModifiers: { evasion: 1 },
    levelRequirement: 5,
  },
  guard_coif: {
    id: "guard_coif",
    displayName: "Guard Coif",
    category: "equipment",
    description: "Tier 1 balanced mail head armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    armorFamily: "mail",
    primaryStatModifiers: { constitution: 1 },
    statModifiers: { defense: 1 },
    levelRequirement: 1,
  },
  guard_hauberk: {
    id: "guard_hauberk",
    displayName: "Guard Hauberk",
    category: "equipment",
    description: "Tier 1 balanced mail chest armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    armorFamily: "mail",
    statModifiers: { defense: 3, maxHealth: 2, evasion: -1 },
    levelRequirement: 1,
  },
  guard_legguards: {
    id: "guard_legguards",
    displayName: "Guard Legguards",
    category: "equipment",
    description: "Tier 1 balanced mail leg armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    armorFamily: "mail",
    primaryStatModifiers: { constitution: 1 },
    statModifiers: { defense: 2, evasion: -1 },
    levelRequirement: 1,
  },
  guard_gloves: {
    id: "guard_gloves",
    displayName: "Guard Gloves",
    category: "equipment",
    description: "Tier 1 balanced mail gloves.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    armorFamily: "mail",
    statModifiers: { block: 1, defense: 1 },
    levelRequirement: 1,
  },
  guard_boots: {
    id: "guard_boots",
    displayName: "Guard Boots",
    category: "equipment",
    description: "Tier 1 balanced mail boots.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    armorFamily: "mail",
    statModifiers: { defense: 1, maxHealth: 1 },
    levelRequirement: 1,
  },
  vanguard_coif: {
    id: "vanguard_coif",
    displayName: "Vanguard Coif",
    category: "equipment",
    description: "Tier 1 offense-leaning mail head armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    armorFamily: "mail",
    primaryStatModifiers: { strength: 1 },
    statModifiers: { defense: 1 },
    levelRequirement: 5,
  },
  vanguard_hauberk: {
    id: "vanguard_hauberk",
    displayName: "Vanguard Hauberk",
    category: "equipment",
    description: "Tier 1 offense-leaning mail chest armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    armorFamily: "mail",
    statModifiers: { attack: 1, defense: 2, evasion: -1 },
    levelRequirement: 5,
  },
  vanguard_legguards: {
    id: "vanguard_legguards",
    displayName: "Vanguard Legguards",
    category: "equipment",
    description: "Tier 1 offense-leaning mail leg armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    armorFamily: "mail",
    primaryStatModifiers: { strength: 1 },
    statModifiers: { defense: 1 },
    levelRequirement: 5,
  },
  vanguard_gloves: {
    id: "vanguard_gloves",
    displayName: "Vanguard Gloves",
    category: "equipment",
    description: "Tier 1 offense-leaning mail gloves.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    armorFamily: "mail",
    statModifiers: { attack: 2 },
    levelRequirement: 5,
  },
  vanguard_boots: {
    id: "vanguard_boots",
    displayName: "Vanguard Boots",
    category: "equipment",
    description: "Tier 1 offense-leaning mail boots.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    armorFamily: "mail",
    statModifiers: { defense: 1, accuracy: 1, evasion: -1 },
    levelRequirement: 5,
  },
  bulwark_helm: {
    id: "bulwark_helm",
    displayName: "Bulwark Helm",
    category: "equipment",
    description: "Tier 1 mitigation-focused plate head armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    armorFamily: "plate",
    statModifiers: { defense: 2, block: 1, evasion: -1 },
    levelRequirement: 10,
  },
  bulwark_cuirass: {
    id: "bulwark_cuirass",
    displayName: "Bulwark Cuirass",
    category: "equipment",
    description: "Tier 1 mitigation-focused plate chest armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    armorFamily: "plate",
    statModifiers: { defense: 4, maxHealth: 3, evasion: -2 },
    levelRequirement: 10,
  },
  bulwark_greaves: {
    id: "bulwark_greaves",
    displayName: "Bulwark Greaves",
    category: "equipment",
    description: "Tier 1 mitigation-focused plate leg armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    armorFamily: "plate",
    primaryStatModifiers: { constitution: 1 },
    statModifiers: { defense: 3, evasion: -2 },
    levelRequirement: 10,
  },
  bulwark_gauntlets: {
    id: "bulwark_gauntlets",
    displayName: "Bulwark Gauntlets",
    category: "equipment",
    description: "Tier 1 mitigation-focused plate gloves.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    armorFamily: "plate",
    statModifiers: { defense: 1, block: 2, evasion: -1 },
    levelRequirement: 10,
  },
  bulwark_sabatons: {
    id: "bulwark_sabatons",
    displayName: "Bulwark Sabatons",
    category: "equipment",
    description: "Tier 1 mitigation-focused plate boots.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    armorFamily: "plate",
    statModifiers: { defense: 2, maxHealth: 1, evasion: -1 },
    levelRequirement: 10,
  },
  warplate_helm: {
    id: "warplate_helm",
    displayName: "Warplate Helm",
    category: "equipment",
    description: "Tier 1 offense-leaning plate head armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    armorFamily: "plate",
    primaryStatModifiers: { strength: 1 },
    statModifiers: { defense: 2, evasion: -1 },
    levelRequirement: 10,
  },
  warplate_cuirass: {
    id: "warplate_cuirass",
    displayName: "Warplate Cuirass",
    category: "equipment",
    description: "Tier 1 offense-leaning plate chest armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    armorFamily: "plate",
    statModifiers: { attack: 1, defense: 3, evasion: -2 },
    levelRequirement: 10,
  },
  warplate_greaves: {
    id: "warplate_greaves",
    displayName: "Warplate Greaves",
    category: "equipment",
    description: "Tier 1 offense-leaning plate leg armor.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    armorFamily: "plate",
    primaryStatModifiers: { strength: 1 },
    statModifiers: { defense: 2, evasion: -2 },
    levelRequirement: 10,
  },
  warplate_gauntlets: {
    id: "warplate_gauntlets",
    displayName: "Warplate Gauntlets",
    category: "equipment",
    description: "Tier 1 offense-leaning plate gloves.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    armorFamily: "plate",
    statModifiers: { attack: 2, defense: 1, evasion: -1 },
    levelRequirement: 10,
  },
  warplate_sabatons: {
    id: "warplate_sabatons",
    displayName: "Warplate Sabatons",
    category: "equipment",
    description: "Tier 1 offense-leaning plate boots.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    armorFamily: "plate",
    statModifiers: { defense: 2, accuracy: 1, evasion: -1 },
    levelRequirement: 10,
  },
  plain_charm: {
    id: "plain_charm",
    displayName: "Plain Charm",
    category: "equipment",
    description: "Prototype shared accessory.",
    tier: 1,
    stackable: false,
    maxStack: 1,
    equipmentSlot: "accessory1",
    equipmentKind: "accessory",
    equipmentType: "accessory",
    statModifiers: { maxHealth: 1 },
    levelRequirement: 1,
  },
};

export function getItemDefinition(itemId: ItemId): ItemDefinition {
  return ITEM_DEFINITIONS[itemId];
}

export function getItemDefinitionForResourceType(
  resourceType: ResourceType,
  tier: LootTier = 1,
): ItemDefinition {
  return getItemDefinition(getResourceItemId(resourceType, tier));
}

function getResourceItemId(resourceType: ResourceType, tier: LootTier): ItemId {
  if (tier === 2) {
    return resourceType === "wood"
      ? "hardwood"
      : resourceType === "ore"
        ? "iron_ore"
        : "redleaf_herb";
  }

  return resourceType === "wood"
    ? "softwood"
    : resourceType === "ore"
      ? "copper_ore"
      : "field_herb";
}
