import type { ItemDefinition, ItemId, ResourceType } from "./types";

export const ITEM_DEFINITIONS: Record<ItemId, ItemDefinition> = {
  wood: {
    id: "wood",
    displayName: "Wood",
    category: "material",
    description: "Prototype gathered wood material.",
    rarity: "common",
    stackable: true,
    maxStack: 250,
  },
  ore: {
    id: "ore",
    displayName: "Ore",
    category: "material",
    description: "Prototype gathered ore material.",
    rarity: "common",
    stackable: true,
    maxStack: 250,
  },
  herb: {
    id: "herb",
    displayName: "Herb",
    category: "material",
    description: "Prototype gathered herb material.",
    rarity: "common",
    stackable: true,
    maxStack: 250,
  },
  training_sword: {
    id: "training_sword",
    displayName: "Training Sword",
    category: "equipment",
    description: "Simple starter sword for Beginners.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "training_sword",
    allowedClassIds: ["beginner"],
    statModifiers: { attack: 1 },
  },
  iron_sword: {
    id: "iron_sword",
    displayName: "Iron Sword",
    category: "equipment",
    description: "Prototype one-handed sword for Blades.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "one_handed_sword",
    allowedClassIds: ["blade"],
    statModifiers: { attack: 2 },
  },
  training_mace: {
    id: "training_mace",
    displayName: "Training Mace",
    category: "equipment",
    description: "Prototype one-handed mace for Aegis companions.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "one_handed_mace",
    allowedClassIds: ["aegis"],
    statModifiers: { attack: 1, defense: 1 },
  },
  claw_gauntlets: {
    id: "claw_gauntlets",
    displayName: "Claw Gauntlets",
    category: "equipment",
    description: "Prototype both-hands melee weapon for Beasts.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "claw_gauntlets",
    allowedClassIds: ["beast"],
    statModifiers: { attack: 2, evasion: 1 },
    occupiesBothHands: true,
  },
  thorn_whip: {
    id: "thorn_whip",
    displayName: "Thorn Whip",
    category: "equipment",
    description: "Prototype risky main-hand weapon for Penitents.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "thorn_whip",
    allowedClassIds: ["penitent"],
    statModifiers: { attack: 2, healingPower: 1 },
  },
  short_bow: {
    id: "short_bow",
    displayName: "Short Bow",
    category: "equipment",
    description: "Prototype both-hands weapon for Hunters.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "bow",
    allowedClassIds: ["hunter"],
    statModifiers: { attack: 2 },
    occupiesBothHands: true,
  },
  apprentice_orb: {
    id: "apprentice_orb",
    displayName: "Apprentice Orb",
    category: "equipment",
    description: "Prototype offensive focus for Elementalists.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "orb",
    allowedClassIds: ["elementalist"],
    statModifiers: { magicPower: 2 },
  },
  rune_lantern: {
    id: "rune_lantern",
    displayName: "Rune Lantern",
    category: "equipment",
    description: "Prototype main-hand focus for Runecasters.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "rune_lantern",
    allowedClassIds: ["runecaster"],
    statModifiers: { magicPower: 1, defense: 1 },
  },
  holy_mace: {
    id: "holy_mace",
    displayName: "Holy Mace",
    category: "equipment",
    description: "Prototype main-hand weapon for Lightbearers.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "mainHand",
    equipmentKind: "weapon",
    equipmentType: "holy_mace",
    allowedClassIds: ["lightbearer"],
    statModifiers: { attack: 1, healingPower: 1 },
  },
  wooden_shield: {
    id: "wooden_shield",
    displayName: "Wooden Shield",
    category: "equipment",
    description: "Prototype shield for Aegis companions.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "shield",
    allowedClassIds: ["aegis"],
    statModifiers: { defense: 1, block: 1 },
  },
  simple_talisman: {
    id: "simple_talisman",
    displayName: "Simple Talisman",
    category: "equipment",
    description: "Prototype offhand talisman for Runecasters.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "talisman",
    allowedClassIds: ["runecaster"],
    statModifiers: { magicPower: 1 },
  },
  holy_lantern: {
    id: "holy_lantern",
    displayName: "Holy Lantern",
    category: "equipment",
    description: "Prototype offhand lantern for Lightbearers.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "holy_lantern",
    allowedClassIds: ["lightbearer"],
    statModifiers: { healingPower: 2 },
  },
  sacrificial_dagger: {
    id: "sacrificial_dagger",
    displayName: "Sacrificial Dagger",
    category: "equipment",
    description: "Prototype offhand dagger for Penitents.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "offhand",
    equipmentKind: "offhand",
    equipmentType: "sacrificial_dagger",
    allowedClassIds: ["penitent"],
    statModifiers: { attack: 1 },
  },
  cloth_cap: {
    id: "cloth_cap",
    displayName: "Cloth Cap",
    category: "equipment",
    description: "Prototype shared head armor.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "head",
    equipmentKind: "armor",
    equipmentType: "head_armor",
    statModifiers: { defense: 1 },
  },
  padded_chest: {
    id: "padded_chest",
    displayName: "Padded Chest",
    category: "equipment",
    description: "Prototype shared chest armor.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "chest",
    equipmentKind: "armor",
    equipmentType: "chest_armor",
    statModifiers: { defense: 2 },
  },
  padded_legs: {
    id: "padded_legs",
    displayName: "Padded Legs",
    category: "equipment",
    description: "Prototype shared leg armor.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "legs",
    equipmentKind: "armor",
    equipmentType: "legs_armor",
    statModifiers: { defense: 1 },
  },
  cloth_gloves: {
    id: "cloth_gloves",
    displayName: "Cloth Gloves",
    category: "equipment",
    description: "Prototype shared gloves.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "gloves",
    equipmentKind: "armor",
    equipmentType: "gloves_armor",
    statModifiers: { defense: 1 },
  },
  travel_boots: {
    id: "travel_boots",
    displayName: "Travel Boots",
    category: "equipment",
    description: "Prototype shared boots.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "boots",
    equipmentKind: "armor",
    equipmentType: "boots_armor",
    statModifiers: { evasion: 1 },
  },
  plain_charm: {
    id: "plain_charm",
    displayName: "Plain Charm",
    category: "equipment",
    description: "Prototype shared accessory.",
    stackable: false,
    maxStack: 1,
    equipmentSlot: "accessory1",
    equipmentKind: "accessory",
    equipmentType: "accessory",
    statModifiers: { maxHealth: 1 },
  },
};

export function getItemDefinition(itemId: ItemId): ItemDefinition {
  return ITEM_DEFINITIONS[itemId];
}

export function getItemDefinitionForResourceType(
  resourceType: ResourceType,
): ItemDefinition {
  return getItemDefinition(resourceType);
}
