import type { ClassId, SkillDefinition } from "./types";

const BEGINNER_SKILL_COOLDOWN_MS = 10000;
const BEGINNER_BUFF_DURATION_MS = 9000;
const FIRST_CLASS_LONG_BUFF_DURATION_MS = 60000;
const FIRST_CLASS_LONG_BUFF_COOLDOWN_MS = 58000;
const FIRST_CLASS_BUFF_REFRESH_WINDOW_MS = 2000;
export const DEFAULT_SKILL_COOLDOWN_MS = 10000;

export const SKILL_DEFINITIONS: Record<SkillDefinition["id"], SkillDefinition> = {
  throw_rock: {
    id: "throw_rock",
    classId: "beginner",
    displayName: "Throw Rock",
    tags: ["Offensive", "Single Target", "Taunt"],
    type: "active",
    range: 4,
    cooldownMs: BEGINNER_SKILL_COOLDOWN_MS,
    effect: { type: "taunt" },
  },
  kick: {
    id: "kick",
    classId: "beginner",
    displayName: "Kick",
    tags: ["Offensive", "Damage", "Single Target"],
    type: "active",
    range: 5,
    cooldownMs: BEGINNER_SKILL_COOLDOWN_MS,
    effect: {
      type: "lungeDamage",
      damageType: "physical",
      powerMultiplier: 1,
      lungeDistance: 5,
    },
  },
  guard_up: {
    id: "guard_up",
    classId: "beginner",
    displayName: "Guard Up",
    tags: ["Defensive", "Shield", "Safety"],
    type: "active",
    range: 0,
    cooldownMs: BEGINNER_SKILL_COOLDOWN_MS,
    effect: {
      type: "shieldBlock",
      durationMs: 3000,
      blocks: 1,
      blockedDamageTypes: ["physical"],
    },
  },
  first_aid: {
    id: "first_aid",
    classId: "beginner",
    displayName: "First Aid",
    tags: ["Heal", "Safety"],
    type: "active",
    range: 3,
    cooldownMs: BEGINNER_SKILL_COOLDOWN_MS,
    effect: { type: "heal", powerMultiplier: 5 },
  },
  deep_breath: {
    id: "deep_breath",
    classId: "beginner",
    displayName: "Deep Breath",
    tags: ["Self Buff", "Safety"],
    type: "active",
    range: 0,
    cooldownMs: BEGINNER_SKILL_COOLDOWN_MS,
    effect: {
      type: "selfBuff",
      bonusDamage: 1,
      durationMs: BEGINNER_BUFF_DURATION_MS,
      hpCost: 0,
    },
  },
  rally_call: {
    id: "rally_call",
    classId: "beginner",
    displayName: "Rally Call",
    tags: ["Buff", "Safety"],
    type: "active",
    range: 4,
    cooldownMs: BEGINNER_SKILL_COOLDOWN_MS,
    effect: {
      type: "allyBuff",
      bonusDamage: 1,
      durationMs: BEGINNER_BUFF_DURATION_MS,
    },
  },
  field_hands: {
    id: "field_hands",
    classId: "beginner",
    displayName: "Field Hands",
    tags: ["Gathering", "Resource Buff", "Tool Buff"],
    type: "active",
    range: 0,
    cooldownMs: BEGINNER_SKILL_COOLDOWN_MS,
    effect: {
      type: "gatherBuff",
      bonusGatherSpeed: 1,
      durationMs: BEGINNER_BUFF_DURATION_MS,
    },
  },
  quick_step: {
    id: "quick_step",
    classId: "beginner",
    displayName: "Quick Step",
    tags: ["Mobility", "Dash", "Escape"],
    type: "active",
    range: 0,
    cooldownMs: BEGINNER_SKILL_COOLDOWN_MS,
    effect: { type: "quickStep", distance: 1 },
  },
  duelist_challenge: {
    id: "duelist_challenge",
    classId: "blade",
    displayName: "Duelist Challenge",
    tags: ["Offensive", "Single Target", "Taunt"],
    type: "active",
    range: 4,
    cooldownMs: 12000,
    effect: { type: "taunt" },
  },
  second_wind: {
    id: "second_wind",
    classId: "blade",
    displayName: "Second Wind",
    tags: ["Heal", "Self Healing", "Safety"],
    type: "active",
    range: 0,
    cooldownMs: 30000,
    effect: { type: "selfPercentHeal", healPercent: 20 },
  },
  blade_parry: {
    id: "blade_parry",
    classId: "blade",
    displayName: "Blade Parry",
    tags: ["Defensive", "Safety", "Damage Mitigation"],
    type: "active",
    range: 0,
    cooldownMs: 15000,
    effect: {
      type: "damageMitigation",
      durationMs: 10000,
      mitigationPercent: 50,
      procs: 2,
      mitigatedDamageTypes: ["physical"],
    },
  },
  edge_focus: {
    id: "edge_focus",
    classId: "blade",
    displayName: "Edge Focus",
    tags: ["Offensive", "Self Buff"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "selfBuff",
      bonusDamage: 1,
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      hpCost: 0,
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  press_the_opening: {
    id: "press_the_opening",
    classId: "blade",
    displayName: "Press the Opening",
    tags: ["Offensive", "Party Buff"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "partyClassBuff",
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      physicalDamageBonusPercent: 5,
      primaryStatBonusPercentByStat: { strength: 5 },
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  woodcutter_rhythm: {
    id: "woodcutter_rhythm",
    classId: "blade",
    displayName: "Woodcutter Rhythm",
    tags: ["Gathering", "Resource Buff", "Tool Buff"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "gatherBuff",
      bonusGatherSpeed: 2,
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      resourceType: "wood",
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  flash_step: {
    id: "flash_step",
    classId: "blade",
    displayName: "Flash Step",
    tags: ["Mobility", "Dash", "Escape"],
    type: "active",
    range: 0,
    cooldownMs: 20000,
    effect: { type: "quickStep", distance: 2 },
  },
  sweeping_strike: {
    id: "sweeping_strike",
    classId: "blade",
    displayName: "Sweeping Strike",
    tags: ["Offensive", "Damage", "Single Target", "AoE"],
    type: "active",
    range: 1,
    cooldownMs: 10000,
    effect: {
      type: "sweepingDamage",
      damageType: "physical",
      mainPowerMultiplier: 1.5,
      splashPowerMultiplier: 1,
      splashRange: 1.5,
    },
  },
  shield_challenge: {
    id: "shield_challenge",
    classId: "aegis",
    displayName: "Shield Challenge",
    tags: ["Defensive", "Taunt", "Multi Target"],
    type: "active",
    range: 4,
    cooldownMs: 12000,
    effect: { type: "multiTaunt", maxTargets: 2 },
  },
  hold_fast: {
    id: "hold_fast",
    classId: "aegis",
    displayName: "Hold Fast",
    tags: ["Defensive", "Shield", "Safety", "Damage Mitigation", "Self Buff"],
    type: "active",
    range: 0,
    cooldownMs: 30000,
    effect: {
      type: "holdFast",
      defenseBonusPercent: 25,
      defenseDurationMs: 10000,
      absorbPercentMaxHealth: 10,
      absorbDurationMs: 5000,
      immobilizeDurationMs: 5000,
    },
  },
  guard_wall: {
    id: "guard_wall",
    classId: "aegis",
    displayName: "Guard Wall",
    tags: ["Defensive", "Shield", "Safety"],
    type: "active",
    range: 0,
    cooldownMs: 15000,
    effect: {
      type: "absorbShield",
      durationMs: 10000,
      absorbPercentMaxHealth: 15,
    },
  },
  iron_stance: {
    id: "iron_stance",
    classId: "aegis",
    displayName: "Iron Stance",
    tags: ["Defensive", "Self Buff", "Safety", "Damage Mitigation"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "selfMitigationBuff",
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      mitigationPercent: 10,
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  shield_formation: {
    id: "shield_formation",
    classId: "aegis",
    displayName: "Shield Formation",
    tags: ["Defensive", "Party Buff", "Shield", "Safety", "Damage Mitigation"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "partyClassBuff",
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      mitigationPercent: 8,
      primaryStatBonusPercentByStat: { constitution: 5 },
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  stonebreaker_rhythm: {
    id: "stonebreaker_rhythm",
    classId: "aegis",
    displayName: "Stonebreaker Rhythm",
    tags: ["Gathering", "Resource Buff", "Tool Buff"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "gatherBuff",
      bonusGatherSpeed: 2,
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      resourceType: "ore",
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  shield_rush: {
    id: "shield_rush",
    classId: "aegis",
    displayName: "Shield Rush",
    tags: ["Mobility", "Dash", "Escape"],
    type: "active",
    range: 2,
    cooldownMs: 20000,
    effect: { type: "quickStep", distance: 2 },
  },
  shield_shockwave: {
    id: "shield_shockwave",
    classId: "aegis",
    displayName: "Shield Shockwave",
    tags: ["Defensive", "Control", "AoE", "Taunt", "Damage"],
    type: "active",
    range: 0,
    cooldownMs: 15000,
    effect: {
      type: "shockwave",
      damageType: "physical",
      powerMultiplier: 0.5,
      radius: 2,
      bindDurationMs: 1000,
    },
  },
  pinning_shot: {
    id: "pinning_shot",
    classId: "hunter",
    displayName: "Pinning Shot",
    tags: ["Control", "Single Target", "Safety"],
    type: "active",
    range: 4,
    cooldownMs: 12000,
    effect: { type: "pinningShot", durationMs: 3000 },
  },
  fake_death: {
    id: "fake_death",
    classId: "hunter",
    displayName: "Fake Death",
    tags: ["Defensive", "Safety", "Escape", "Self Buff"],
    type: "active",
    range: 0,
    cooldownMs: 30000,
    effect: {
      type: "fakeDeath",
      fakeDeathDurationMs: 3000,
      nextAttackDamageMultiplierBonus: 0.3,
      nextAttackBonusDurationMs: 10000,
    },
  },
  evasive_instinct: {
    id: "evasive_instinct",
    classId: "hunter",
    displayName: "Evasive Instinct",
    tags: ["Defensive", "Safety", "Damage Mitigation", "Self Buff"],
    type: "active",
    range: 0,
    cooldownMs: 15000,
    effect: { type: "forcedEvasion", durationMs: 10000 },
  },
  hunters_focus: {
    id: "hunters_focus",
    classId: "hunter",
    displayName: "Hunter's Focus",
    tags: ["Offensive", "Self Buff"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "selfBuff",
      bonusDamage: 1,
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      hpCost: 0,
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  poison_coating: {
    id: "poison_coating",
    classId: "hunter",
    displayName: "Poison Coating",
    tags: ["Offensive", "Party Buff", "DoT"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "partyClassBuff",
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      primaryStatBonusPercentByStat: { dexterity: 5 },
      poisonCoating: {
        poisonDurationMs: 4000,
        poisonTickIntervalMs: 2000,
        poisonDamageAttackPowerPercent: 20,
        sourceKey: "poison_coating",
      },
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  herbalist_rhythm: {
    id: "herbalist_rhythm",
    classId: "hunter",
    displayName: "Herbalist Rhythm",
    tags: ["Gathering", "Resource Buff", "Tool Buff"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "gatherBuff",
      bonusGatherSpeed: 2,
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      resourceType: "herb",
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  skirmish_shot: {
    id: "skirmish_shot",
    classId: "hunter",
    displayName: "Skirmish Shot",
    tags: ["Mobility", "Dash", "Escape", "Damage", "Single Target"],
    type: "active",
    range: 4,
    cooldownMs: 20000,
    effect: {
      type: "skirmishShot",
      distance: 2,
      damageType: "physical",
      powerMultiplier: 1,
    },
  },
  arrow_burst: {
    id: "arrow_burst",
    classId: "hunter",
    displayName: "Arrow Burst",
    tags: ["Offensive", "Damage", "Multi Target", "AoE"],
    type: "active",
    range: 4,
    cooldownMs: 15000,
    effect: {
      type: "arrowBurst",
      damageType: "physical",
      powerMultiplier: 1.1,
      radius: 3,
    },
  },
  threatening_roar: {
    id: "threatening_roar",
    classId: "beast",
    displayName: "Threatening Roar",
    tags: ["Defensive", "Taunt", "Control", "AoE"],
    type: "active",
    range: 3,
    cooldownMs: 15000,
    effect: { type: "multiTaunt", maxTargets: 2 },
  },
  blood_feast: {
    id: "blood_feast",
    classId: "beast",
    displayName: "Blood Feast",
    tags: ["Heal", "Self Healing", "Safety", "Offensive", "Self Buff"],
    type: "active",
    range: 0,
    cooldownMs: 30000,
    effect: {
      type: "lifestealBuff",
      durationMs: 8000,
      lifestealPercent: 10,
    },
  },
  rugged_hide: {
    id: "rugged_hide",
    classId: "beast",
    displayName: "Rugged Hide",
    tags: ["Defensive", "Safety", "Damage Mitigation", "Self Buff"],
    type: "active",
    range: 0,
    cooldownMs: 20000,
    effect: {
      type: "selfMitigationBuff",
      durationMs: 10000,
      mitigationPercent: 20,
    },
  },
  feral_surge: {
    id: "feral_surge",
    classId: "beast",
    displayName: "Feral Surge",
    tags: ["Offensive", "Self Buff", "Mobility"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "selfBuff",
      bonusDamage: 1,
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      hpCost: 0,
      movementSpeedBonusPercent: 20,
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  pack_frenzy: {
    id: "pack_frenzy",
    classId: "beast",
    displayName: "Pack Frenzy",
    tags: ["Offensive", "Party Buff"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "partyClassBuff",
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      primaryStatBonusPercentByStat: { strength: 5, dexterity: 5 },
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  stoneclaw_rhythm: {
    id: "stoneclaw_rhythm",
    classId: "beast",
    displayName: "Stoneclaw Rhythm",
    tags: ["Gathering", "Resource Buff", "Tool Buff"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "gatherBuff",
      bonusGatherSpeed: 2,
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      resourceType: "ore",
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  pounce: {
    id: "pounce",
    classId: "beast",
    displayName: "Pounce",
    tags: ["Mobility", "Dash", "Escape", "Damage", "Single Target"],
    type: "active",
    range: 4,
    cooldownMs: 20000,
    effect: {
      type: "pounce",
      distance: 2,
      damageType: "physical",
      powerMultiplier: 1,
    },
  },
  maul_sweep: {
    id: "maul_sweep",
    classId: "beast",
    displayName: "Maul Sweep",
    tags: ["Offensive", "Damage", "AoE", "Multi Target", "Control"],
    type: "active",
    range: 0,
    cooldownMs: 15000,
    effect: {
      type: "maulSweep",
      damageType: "physical",
      powerMultiplier: 0.9,
      radius: 2,
      disarmDurationMs: 1500,
    },
  },
  elemental_bolt: {
    id: "elemental_bolt",
    classId: "elementalist",
    displayName: "Elemental Bolt",
    tags: ["Offensive", "Damage", "Single Target"],
    type: "active",
    range: 5,
    cooldownMs: 12000,
    effect: { type: "damage", damageType: "magic", powerMultiplier: 1.25 },
  },
  mana_shield: {
    id: "mana_shield",
    classId: "elementalist",
    displayName: "Mana Shield",
    tags: ["Defensive", "Shield", "Safety", "Maintenance"],
    type: "active",
    range: 0,
    cooldownMs: 30000,
    effect: { type: "manaShield", absorbPercentMaxHealth: 15 },
  },
  frost_armor: {
    id: "frost_armor",
    classId: "elementalist",
    displayName: "Frost Armor",
    tags: ["Defensive", "Buff", "Safety", "Damage Mitigation"],
    type: "active",
    range: 5,
    cooldownMs: 6000,
    effect: {
      type: "frostArmor",
      durationMs: 20000,
      defenseBonusPercent: 10,
      mitigationPercent: 10,
    },
  },
  overcharge: {
    id: "overcharge",
    classId: "elementalist",
    displayName: "Overcharge",
    tags: ["Offensive", "Self Buff", "Maintenance"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "overcharge",
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      skillPowerBonusPercent: 10,
      cooldownPenaltyPercent: 20,
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  arcane_conduit: {
    id: "arcane_conduit",
    classId: "elementalist",
    displayName: "Arcane Conduit",
    tags: ["Offensive", "Party Buff"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "partyClassBuff",
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      magicDamageBonusPercent: 5,
      primaryStatBonusPercentByStat: { intelligence: 5 },
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  emberwood_rhythm: {
    id: "emberwood_rhythm",
    classId: "elementalist",
    displayName: "Emberwood Rhythm",
    tags: ["Gathering", "Resource Buff", "Tool Buff"],
    type: "active",
    range: 0,
    cooldownMs: FIRST_CLASS_LONG_BUFF_COOLDOWN_MS,
    effect: {
      type: "gatherBuff",
      bonusGatherSpeed: 2,
      durationMs: FIRST_CLASS_LONG_BUFF_DURATION_MS,
      resourceType: "wood",
      refreshWindowMs: FIRST_CLASS_BUFF_REFRESH_WINDOW_MS,
    },
  },
  flame_step: {
    id: "flame_step",
    classId: "elementalist",
    displayName: "Flame Step",
    tags: ["Mobility", "Dash", "Escape", "Damage", "DoT", "Single Target"],
    type: "active",
    range: 5,
    cooldownMs: 20000,
    effect: {
      type: "flameStep",
      distance: 2,
      burnDurationMs: 4000,
      burnTickIntervalMs: 2000,
      burnDamageMagicPowerPercent: 20,
      sourceKey: "flame_step",
    },
  },
  fire_burst: {
    id: "fire_burst",
    classId: "elementalist",
    displayName: "FireBurst",
    tags: ["Offensive", "Damage", "Multi Target", "AoE", "DoT"],
    type: "active",
    range: 5,
    cooldownMs: 15000,
    effect: {
      type: "fireBurst",
      damageType: "magic",
      powerMultiplier: 1,
      radius: 3,
      burnDurationMs: 4000,
      burnTickIntervalMs: 2000,
      burnDamageMagicPowerPercent: 20,
      sourceKey: "fire_burst",
    },
  },
  binding_rune: {
    id: "binding_rune",
    classId: "runecaster",
    displayName: "Binding Rune",
    tags: ["Control", "Trap", "Safety"],
    type: "active",
    range: 4,
    effect: { type: "bind", durationMs: 3000 },
  },
  light_mend: {
    id: "light_mend",
    classId: "lightbearer",
    displayName: "Light Mend",
    tags: ["Heal", "Safety"],
    type: "active",
    range: 4,
    effect: { type: "heal", powerMultiplier: 1.5 },
  },
  penitents_gift: {
    id: "penitents_gift",
    classId: "penitent",
    displayName: "Penitent's Gift",
    tags: ["Heal", "Self Cost - HP", "Safety"],
    type: "active",
    range: 4,
    effect: { type: "selfCostHeal", powerMultiplier: 2, hpCost: 1 },
  },
};

export function getSkillsForClass(classId: ClassId): SkillDefinition[] {
  return Object.values(SKILL_DEFINITIONS).filter(
    (skill) => skill.classId === classId,
  );
}

export function getSkillCooldownMs(skill: SkillDefinition): number {
  return skill.cooldownMs ?? DEFAULT_SKILL_COOLDOWN_MS;
}
